### ISSUE TITLE
archive

### ISSUE THREAD

**Issue by sensoroDj** [winstonjs/winston-daily-rotate-file#10]
no zippedArchive options

**Comment by mattberther** [comment]
Thanks for the report @sensoroDj. This was documented on the `winston` repository as https://github.com/winstonjs/winston/issues/682. Since the `winston-daily-rotate-file` is now in its own repo, we should continue the conversation here.

**Comment by mattberther** [comment]
I brought over the issue from winston as #20 - also, the pull request is ready at #25.
