### ISSUE TITLE
Compatibility with cluster module

### ISSUE THREAD

**Issue by sumitjainn** [winstonjs/winston-daily-rotate-file#102]
Is daily rotate file compatible with node cluster module?

**Comment by mattberther** [comment]
@sumitjainn This has not been tested. I do not see any reason why it wouldnt be. However, if you use it and identify an issue, please feel free to open a new issue describing expected vs actual behavior.

**Comment by sumitjainn** [comment]
There could potentially be a issue if multiple worker processes try to rotate the file at the same time. I tried testing it and didn't get the issue.. but just wanted to be sure before using it in production.

**Comment by sumitjainn** [comment]
I get this error when running 4 instances of my app simultaneously

fs.js:1104
  return binding.unlink(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, unlink 'app-1-2017-10-25_06-15.log'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:1104:18)
    at compressFile (/home/sumit/work/projects/winston/node_modules/winston-daily-rotate-file/index.js:617:12)
    at createAndFlush (/home/sumit/work/projects/winston/node_modules/winston-daily-rotate-file/index.js:604:7)
    at /home/sumit/work/projects/winston/node_modules/winston-daily-rotate-file/index.js:627:16
    at FSReqWrap.oncomplete (fs.js:123:15)

Wouldn't the same thing happen if I run the app through cluster module with 4 workers?

**Comment by mattberther** [comment]
Something like the code below should support the cluster module.

``` javascript
var cluster = require('cluster');
var http = require('http');
var winston = require('winston');
require('winston-daily-rotate-file');

if (cluster.isMaster) {
  var logger = new (winston.Logger)({
      transports: [
          new (winston.transports.Console)(),
          new winston.transports.DailyRotateFile({
                filename: 'log',
                level: 'info',
                json: false,
                maxSize: 1024
            })
      ]
  });

  function messageHandler(msg) {
    if (msg) {
      logger.log(msg.level, msg.message);
    }
  }

  var cpus = require('os').cpus().length;
  for (var i = 0; i < cpus; i++) {
    cluster.fork();
  }

  for (var id in cluster.workers) {
    cluster.workers[id].on('message', messageHandler);
  }
} else {
  http.Server((req, res) => {
    res.writeHead(200);
    res.end('hello world\n');

    // send the message the cluster master
    process.send({level: 'info', message: 'Request received: ' + req});
  }).listen(8000);
}
```
