### ISSUE TITLE
maxsize and maxfiles attributes not working unless process is restarted.

### ISSUE THREAD

**Issue by dsomesh** [winstonjs/winston-daily-rotate-file#105]
I have a configuration saying that log size should be 10 MB at max. Still I see that when the process restarts only then this constraint is applied and new logs are created accordingly.The the process is already running and the log size gets more than the permissible limit,shouldn't the log be recreated at the same time?

**Comment by mattberther** [comment]
Hello @dsomesh. The max size and maxfile attributes are sent to the transport when it is initialized. Unless the transport is re-initialized, there is no way to update the attributes.

**Comment by dsomesh** [comment]
Maybe I did not convey the problem properly.What I meant was the transport is initialized when the process starts.I am not modifying the configurations again.But,the same configurations are not taking effect if the log size goes more than the specified value.It only creates a new log next time the process starts.My doubt is ,does it check the log filesize(against maxsize attribute) only at transport initialization time or it checks for that every time something is written into the log.

**Comment by mattberther** [comment]
Thank you for the clarification.

Some long-overdue refactoring of the transport has occurred. A PR is available at #107. Also, a pre-release version has been published to npm. Please `npm install winston-daily-rotate-file@2.0.0-beta` and reopen this issue if the problem remains.
