### ISSUE TITLE
Winston 3.0 compatibility

### ISSUE THREAD

**Issue by mattberther** [winstonjs/winston-daily-rotate-file#106]
Winston 3.0-rc introduced some breaking changes to the transport plugin model. As a result, the current version of winston-daily-rotate-file does not work with winston >= 3.

The current workaround is to avoid upgrading to winston 3.0. However, a fix is being worked on to allow for compatibility with current and previous versions of winston.

**Comment by levz0r** [comment]
Hi @mattberther, can you please share the status of this feature? ETA?

Thank you.

**Comment by sgilligan** [comment]
+1

**Comment by Sparki2002** [comment]
+1

**Comment by MatthewTrout** [comment]
+1

**Comment by bouchezb** [comment]
Hello @mattberther can you tell us if this feature is being released soon ?
I don't want to downgrade to winston 2.x only because of this. :sweat_smile: 

Thanks.

**Comment by mattberther** [comment]
This is available in #107 now. Ive published an rc to npm. Please `npm install winston-daily-rotate-file@2.0.0-rc.1` and report back any issues you encounter to this ticket please.

**Comment by rylancates** [comment]
Will be looking at this version today.

I'm migrating from winston ^2.4.0 and winston-daily-rotate-file ^1.7.2. Anything in particular to watch out for? (specific to this package)

**Comment by mattberther** [comment]
@rylancates You'll want to review the documentation updates at #107, specifically, https://github.com/winstonjs/winston-daily-rotate-file/commit/407f0cba2504b8a112f8860f977d5774342792fa. Some of the 1.7.2 options have been removed/renamed. All the new options are detailed at the commit mentioned.

**Comment by rylancates** [comment]
@mattberther Thanks, that was helpful. So far so good. Daily rotate appears to be working as expected.

**Comment by colepatrickturner** [comment]
Hello I believe there is an issue with `maxSize` per the new spec.

The options I used are `maxSize: 20 * 1024 * 1024` and `maxSize: '20m'`. Instead of re-using the file, it would rotate on each request, doing error-YYYY-MM-HH.log.1 and counting up.

Without `maxSize` it works correctly 👍 

Thanks for your time!

**Comment by mattberther** [comment]
@colepatrickturner Can you provide a small example demonstrating the issue? The following test code for me only creates a single file:

```javascript
var winston = require('winston');
var DailyRotateFile = require('winston-daily-rotate-file');

var logger = winston.createLogger();
logger.add(new DailyRotateFile({
    filename: 'test.%DATE%.log',
    maxSize: '20m'
}));

logger.info(randomString(1025));
logger.info(randomString(1025));
logger.info(randomString(1025));

**Comment by rylancates** [comment]
Forgive me if this isn't the case, but as I missed this initially as well before doing further reading. I feel like @colepatrickturner may be unaware that there is a newer release candidate addressing this issue.

This thread suggests installing `winston-daily-rotate-file@2.0.0-rc.1`, whereas pr #107 contains information on a newer package that - I believe - addresses this bug as reported by @bouchezb .

[This comment](https://github.com/winstonjs/winston-daily-rotate-file/pull/107#issuecomment-362366591) has the new candidate package version: `winston-daily-rotate-file@2.0.0-rc.2`.

I hope this helps!

**Comment by gravitycode** [comment]
+1

**Comment by mattberther** [comment]
#107 merged and updated package pushed to npm. Please `npm install winston-daily-rotate-file@3` to have winston 3.x compatibility.

This project also bumped to version 3 in an effort to stay consistent with the winston version.
