### ISSUE TITLE
When does it start zipping logs?

### ISSUE THREAD

**Issue by theonlygusti** [winstonjs/winston-daily-rotate-file#108]

**Comment by mattberther** [comment]
It zips the logs after rotation. Please note that some long-overdue refactoring of the transport has occurred. A PR is available at #107. Also, a pre-release version has been published to npm. Please npm install winston-daily-rotate-file@2.0.0-beta if you see any strangeness with the 1.x transport and zipping.

Please re-open this issue if you have further questions.

**Comment by theonlygusti** [comment]
It zips after one day?

I have many .log files from months ago.

Does the application have to run continually for it to zip them up daily?

Maybe it should become a feature where, upon starting, it can detect old log files and zip them up.

**Comment by mattberther** [comment]
The application will zip the log after it is rotated, assuming `zippedArchive` is set to true. The transport will not modify any files it does not know about, which means it will not zip up log files that were not created by the currently running process.

**Comment by theonlygusti** [comment]
Is it possible to make it so that it does zip up log files that were generated by previous instances of the same app?

**Comment by mattberther** [comment]
The transport will not be updated to zip up log files that the currently running process did not create. Perhaps this is something that your app can do prior to instantiating the winston logger.

**Comment by theonlygusti** [comment]
Would it be possible to expose a method for zipping the current log?

Then this method could be called when the process is exited.

**Comment by mattberther** [comment]
No, but your app code zip logs using this code:

``` javascript
var zlib = require('zlib');
var oldFile = someMethodToRetrieveYourFile();

var gzip = zlib.createGzip();
var inp = fs.createReadStream(oldFile);
var out = fs.createWriteStream(oldFile + '.gz');
inp.pipe(gzip).pipe(out).on('finish', function () {
    fs.unlinkSync(oldFile);
});
```
