### ISSUE TITLE
Timezone - time recorded in file

### ISSUE THREAD

**Issue by albert47** [winstonjs/winston-daily-rotate-file#109]
It seems like the timezone recorded in the file is not the same as the filename when 'localTime' is set to true.  Is there a way to record the localTime in the timestamp instead of UTC time?

**Comment by mattberther** [comment]
@albert47 Some long-overdue refactoring of the transport has occurred. A PR is available at #107. Also, a pre-release version has been published to npm. Please npm install winston-daily-rotate-file@2.0.0-beta and re-open this issue if you still see any strangeness with the transport and timezones.
