### ISSUE TITLE
How to specify Max File size

### ISSUE THREAD

**Issue by ravigore** [winstonjs/winston-daily-rotate-file#111]
var transport = new (winston.transports.DailyRotateFile)({
    filename: './log',
    datePattern: 'yyyy-MM-dd.',
    prepend: true,
    level: process.env.ENV === 'development' ? 'debug' : 'info'
  });

But i want to new file if file size exceed 10 mb

**Comment by mattberther** [comment]
Some long-overdue refactoring of the transport has occurred. A PR is available at #107. Also, a pre-release version has been published to npm. Please `npm install winston-daily-rotate-file@2.0.0-beta` and set `maxSize: '10m'`
