### ISSUE TITLE
ERROR TypeError: fs.readdir is not a function

### ISSUE THREAD

**Issue by NewbieAngular** [winstonjs/winston-daily-rotate-file#115]
This is the source Code 

```
var winston = require('winston');
require('winston-daily-rotate-file');
const tsFormat = () => (new Date()).toLocaleTimeString();

var transport = new (winston.transports.DailyRotateFile)({
  filename: './log',
  datePattern: 'yyyy-MM-dd.',
  prepend: true,
  timestamp: tsFormat,
  level:   'debug',
  maxDays:60,
  file: new winston.transports.File({ filename: 'Access.log', level: 'debug' })

});

var logger = new (winston.Logger)({
  transports: [
    transport
  ]
});
```

Getting the error "`ERROR TypeError: fs.readdir is not a function`"

If I remove the '`maxDays:60`' option, I don't see this error . However, another one pops up.

`TypeError: fs.stat is not a function`

**Comment by NewbieAngular** [comment]
version: "winston-daily-rotate-file": "^1.7.2",

**Comment by mattberther** [comment]
The fs module is a core part of nodejs. Please tell me more about the application, including nodejs version, you are trying to log against.

**Comment by NewbieAngular** [comment]
5.5.1

**Comment by NewbieAngular** [comment]
I am trying to make this a reusable logger component, so that any application can use this to log their events.

**Comment by mattberther** [comment]
What happens when you run this code against your node environment?

``` javascript
var fs = require('fs');
fs.readdir('.', function(err, files) {
    console.log(files);
});
```

**Comment by NewbieAngular** [comment]
Uncaught (in promise): TypeError: fs.readdir is not a function
TypeError: fs.readdir is not a function

**Comment by mattberther** [comment]
This leads me to speculate a problem with your node installation. I’m going to close this issue. Feel free to reopen when you can make the code above run without error.

**Comment by sumits99** [comment]
please help i have same issue but on client side rendering using browserify.

I have no error on server side.

**Comment by mattberther** [comment]
What happens when you run the code from https://github.com/winstonjs/winston-daily-rotate-file/issues/115#issuecomment-350313078 through browserify?

**Comment by Hantick** [comment]
vue.runtime.esm.js?2b0e:1888 TypeError: fs.readdir is not a function
when running this function in mounted() section

**Comment by mattberther** [comment]
This does not appear to be an issue with this transport. `fs.readdir` is a low-level node method and there's things that need to happen to allow access to that function through browserify. StackOverflow may help here.

**Comment by mattberther** [comment]
This is still not an issue with this transport. 

From https://stackoverflow.com/questions/70552331/how-to-use-fs-readdirsync-when-using-browserify

> Browserify lets you make modules available in the browser that don't depend on core modules provided by node when run as an executable. [File system](https://nodejs.org/docs/latest/api/fs.html) access using the fs module is one such core module.
