### ISSUE TITLE
Handle exceptions (in)compatibility

### ISSUE THREAD

**Issue by adrifmonte** [winstonjs/winston-daily-rotate-file#117]
Is it fully compatible with [`handleExceptions: true`](https://github.com/winstonjs/winston/tree/2.4.0#handling-uncaught-exceptions-with-winston) option?

In the other hand, `timestamp`, seems to work fine with [the current implementation](https://github.com/winstonjs/winston-daily-rotate-file/blob/master/index.js), as we can see here:

>      (76) this.timestamp = options.timestamp === undefined ? true : options.timestamp;

and here:

>      (223) timestamp: this.timestamp,

but if you search for `handleExceptions`, it has no occurences. Apparently, daily rotate ignores it.

Was it missed? Is there a bug or known incompatibility here?

*Edit:*

Hmm apparently, [`tailable`](https://github.com/winstonjs/winston-daily-rotate-file/issues/23) is also missing!

**Comment by adrifmonte** [comment]
Hmm apparently, [`tailable`](https://github.com/winstonjs/winston-daily-rotate-file/issues/23) is also missing!

**Comment by mattberther** [comment]
Hi @adrifmonte. Tailable support is discussed at #23.

Regarding `handleExceptions`, this is managed by the winston library directly as evidenced by the code below.

```js
 var logger = new (winston.Logger)({
    transports: [
        new winston.transports.DailyRotateFile({
            filename: 'log',
            datePattern: 'YYYY-MM',
            level: 'info',
            handleExceptions: true
        })
    ]
});

throw new Error('testing');
```

Please re-open this issue if you have problems with using `handleExceptions`.
