### ISSUE TITLE
Rotate event

### ISSUE THREAD

**Issue by gilly3** [winstonjs/winston-daily-rotate-file#118]
I would like to log a detailed status message at the top of each log file.  I was hoping that the transport would provide either a "rotate" event that I could listen for, or provide some other mechanism to make sure that each log file contains my status message near the beginning of the file.

Is this feasible?  If I were to submit a pull request, where in the code is the right place to raise such an event?

**Comment by mattberther** [comment]
Some long-overdue refactoring of the transport has occurred. A PR is available at #107. Also, a pre-release version has been published to npm. Please `npm install winston-daily-rotate-file@2.0.0-beta`. This version of the transport emits a `rotate` event.
