### ISSUE TITLE
maxDays not working

### ISSUE THREAD

**Issue by anku10** [winstonjs/winston-daily-rotate-file#119]
```js
const httplogger = new (winston.Logger)({
  transports: [
     new (require('winston-daily-rotate-file'))({
      filename: `${loghttpDir}/-http.log`,
      timestamp: tsFormat,
      localTime:true,
      datePattern: 'yyyy-MM-dd-HH:mm',
      prepend: true,
      colorize: true,
      maxDays:1,
      level: 'info'
    })
  ]
});
```
This is my code . I have set datePattern: 'yyyy-MM-dd-HH:mm', this works fine but also i have set maxDays:1, but it doesn't removes file. I have set 1, then should be remove file after 1 day

**Comment by mattberther** [comment]
This issue was discussed at #91. Please review the resolution there (installing the long-overdue refactored component, noting to set the `maxFiles` property).
