### ISSUE TITLE
maxDays property doesn't work as expected

### ISSUE THREAD

**Issue by maxsakharov** [winstonjs/winston-daily-rotate-file#120]
Hi there!

Looks like the way how `maxDays` property doesn't handled expected for ES3. The problem is [that peace](https://github.com/winstonjs/winston-daily-rotate-file/blob/master/index.js#L845). Regex created once and then tested against all files, however there is known [bug](http://blog.stevenlevithan.com/archives/es3-regexes-broken) for ES3. Which means that half of files will be deleted and half of them will be skipped. It can be easily tested agains local directory with log files. 

For example. If you have next log files in your log directory
```
ls -la /var/log/access
-rw-r--r--   Apr 16  2016 2018-01-25.access.log
-rw-r--r--   Apr 16  2016 2018-01-26.access.log
-rw-r--r--   Apr 16  2016 2018-01-27.access.log
-rw-r--r--   Apr 16  2016 2018-01-28.access.log
-rw-r--r--   Apr 16  2016 2018-01-29.access.log
-rw-r--r--   Jan 31 21:25 2018-01-30.access.log
-rw-r--r--   Jan 31 21:25 2018-01-31.access.log
-rw-r--r--   Jan 31 21:43 2018-02-01.access.log
```

And then you start your app with `winston-daily-rotate-file` transport where `maxDays=3`. It won't clean all of your files, instead it will leave few outdated files and after running your app you'll see next in you logging directory

```
ls -la /var/log/access
-rw-r--r--   Apr 16  2016 2018-01-26.access.log
-rw-r--r--   Apr 16  2016 2018-01-28.access.log
-rw-r--r--   Jan 31 21:25 2018-01-30.access.log
-rw-r--r--   Jan 31 21:25 2018-01-31.access.log
-rw-r--r--   Jan 31 21:43 2018-02-01.access.log
``` 

I think this behaviour is hidden behind potential multiple restarts of the app and other calls of `_cleanOldFiles ` method, but still it seems incorrect to me

**Comment by mattberther** [comment]
This issue was discussed at #91. Please review the resolution there (installing the long-overdue refactored component, noting to set the `maxFiles` property).
