### ISSUE TITLE
Types definitions needed

### ISSUE THREAD

**Issue by praveen001** [winstonjs/winston-daily-rotate-file#121]
I'm trying to use winston-daily-rotate-file with typescript, I just noticed types declarations are not available at [types/winston-daily-rotate-file](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types)

I'm new to typescript, can someone write a proper types declarations for this? 

For now I have added some simple types declarations and everything seems to be working fine. I'm sharing it in case anyone is looking for it.  
```
declare module 'winston-daily-rotate-file' {
  import { DailyRotateFileTransportInstance } from 'winston';
  let DailyRotateFile: DailyRotateFileTransportInstance;
  export = DailyRotateFile;
}
```

**Comment by IWSR** [comment]
I think you can copy the options of DailyRotateFileTransportInstance in "@\type/winston", then publish a package includes these options.

This is an opportunity to increase the number of open source projects, and it will benefit many people who want to use typescript.

[how to publish it to npm](http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html)

**Comment by SirGordon** [comment]
This is a 5 min task, would really appreciate if some1 makes a PR

**Comment by mattberther** [comment]
@SirGordon I've flagged the issue as help-wanted. You're welcome to submit a PR for this 5 minute task. Thank you.

**Comment by SirGordon** [comment]
@mattberther I've never made a d.ts file, actually I do not speak javascript. But I'll try to find time for this.

**Comment by Slessi** [comment]
Haven't had any luck myself. The code supplied by @praveen001 definitely does not work for me, `DailyRotateFileTransportInstance` is not an exported member of the types supplied with the `winston` library.

Tried using [declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) but haven't managed. The below is what I would've *assumed* is required

```typescript
import * as origWinston from "winston";

declare namespace winston {
    interface DailyRotateFileTransportInstance
        extends Pick<
                origWinston.transports.FileTransportInstance,
                Exclude<keyof origWinston.transports.FileTransportInstance, "maxFiles">
            > {
        /**
         * A string representing the moment.js date format to be used for rotating. The meta characters used in this string will dictate the frequency of the file rotation. For example, if your datePattern is simply 'HH' you will end up with 24 log files that are picked up and appended to every day. (default 'YYYY-MM-DD')
         */
        datePattern: string;

        /**
         * A boolean to define whether or not to gzip archived log files. (default 'false')
         */
        zippedArchive: boolean;

        /**
         * Filename to be used to log to. This filename can include the %DATE% placeholder which will include the formatted datePattern at that point in the filename. (default: 'winston.log.%DATE%)
         */
        filename: string;

        /**
         * The directory name to save log files to. (default: '.')
         */
        dirname: string;

        /**
         * Write directly to a custom stream and bypass the rotation capabilities. (default: null)
         */
        stream: null;

        /**
         * Maximum size of the file after which it will rotate. This can be a number of bytes, or units of kb, mb, and gb. If using the units, add 'k', 'm', or 'g' as the suffix. The units need to directly follow the number. (default: null)
         */
        maxSize: string;

        /**
         * Maximum number of logs to keep. If not set, no logs will be removed. This can be a number of files or number of days. If using days, add 'd' as the suffix. (default: null)
         */
        maxFiles: string;
    }

    interface Transports extends origWinston.transports.Transports {
        DailyRotateFile: DailyRotateFileTransportInstance;
    }
}
```

**Comment by Slessi** [comment]
Actually... the following works. Thought the only way to get it was to go through `winston.transports`, but since the package is also exported directly from this package, the following works:

> The `Pick<Exclude<>>` stuff is because `maxFiles` from `winston` doesn't accept a string usually, so I had to extend everything except that property from the definition. I'm assuming it must be a string anyway, since the README here says that u can do things like `maxFiles: '14d'`

```typescript
declare module "winston-daily-rotate-file" {
    import { transports } from "winston";

    interface DailyRotateFileTransportOptions
        extends Pick<transports.FileTransportOptions, Exclude<keyof transports.FileTransportOptions, "maxFiles">> {
        datePattern: string;
        zippedArchive: boolean;
        maxSize: string;
        maxFiles: string;
    }

    interface DailyRotateFileTransportInstance extends transports.FileTransportInstance {
        new (options?: DailyRotateFileTransportOptions): DailyRotateFileTransportInstance;
    }

    const DailyRotateFile: DailyRotateFileTransportInstance;

    export = DailyRotateFile;
}
```

**Comment by mattberther** [comment]
Thanks for the work on this, @Slessi. Only comment I have is that I think we should specify our own options, as I dont want to be dependent on the `FileTransport`.

**Comment by Slessi** [comment]
@mattberther sure, kinda just assumed options were like that, i.e. winston's file options + extra rotate file options

**Comment by mattberther** [comment]
Thanks @Slessi -- and when you're ready, would you mind submitting a PR for this work? Thank you!

**Comment by Slessi** [comment]
will do

**Comment by mattberther** [comment]
Thank you @Slessi. Merged #163 and published to npm as `winston-daily-rotate-file@3.3.0`.

**Comment by samueltlg** [comment]
Hi there,

This may seem a little trivial, but how does one go about importing the type file for this module? I can't seem to get it to work. Using the latest version of vs code and typescript, the only way I can get winston typings to work is:

`import winston from 'node_modules/winston/index'`

No other format works - `import winston from 'winston'` is ineffective.
So that may have something to do with the typings not working for this package; the various forms I have tried after successfully importing winston typings (as in the form above) are:

```javascript
import 'winston-daily-rotate-file`
import 'node_modules/winston-daily-rotate-file'
import 'node_modules/winston-daily-rotate-file/index'
import 'node_modules/winston-daily-rotate-file/index.d.ts'
require('winston-daily-rotate-file')
require('node_modules/winston-daily-rotate-file')
// ...
// ^ All of the same path types that import uses, basically
```

Any ideas?
Thanks, Sam

**Comment by koffmoff** [comment]
@samueltlg , I do it like this:

```ts
import { createLogger } from "winston";
import * as DailyRotateFile from "winston-daily-rotate-file";

const log = createLogger({
    transports: [
        new DailyRotateFile({
            filename: "log/output-%DATE%.log",
            datePattern: "YYYY-MM-DD",
        })
    ]
});
```

**Comment by dreamerkumar** [comment]
@mattberther I don't think this fix works. Slessi's fix defines the interface `DailyRotateFileTransportOptions `and `DailyRotateFileTransportInstance` but only exports the created instance `DailyRotateFile`. The interfaces need to be exported as well. This way, we can create options object of type DailyRotateFileTransportOptions. 
What is missing is the ability to define options like this:
`const dailyRotateOptions: DailyRotateFileTransportOptions = {
..
..
}`

**Comment by Slessi** [comment]
@dreamerkumar I assure you the fix *does* work. I have been using it the same way as @koffmoff without issue.

If you want the interfaces exported you'll have to submit a PR

**Comment by dreamerkumar** [comment]
Created PR to export the interfaces https://github.com/winstonjs/winston-daily-rotate-file/pull/189
