### ISSUE TITLE
[winston 2.x] fails when logging with metadata (json:false)

### ISSUE THREAD

**Issue by lpfeup** [winstonjs/winston-daily-rotate-file#123]
example code:

```javascript
const winston = require('winston');
const RollingFileTransport = require('winston-daily-rotate-file');

const options = {
	json: false, 
	timestamp: function() {
		return new Date().toISOString().substring(0, 16).replace('T',' ');
	}
};

const rollingFileTransportOptions = {
	filename: 'test-%DATE%.log',
	datePattern: 'YYYY-MM-DD',
	maxFiles: 30
};

const logger = new (winston.Logger)({
	level: 'info',
	transports: [
		new winston.transports.Console(options),
		new RollingFileTransport(Object.assign({}, rollingFileTransportOptions, options))
	]
});


// works
logger.info('test');

// fails with exception
logger.info('test', {myIntField:1});
```

error:

```        
output += ' ' + exports.serialize(meta);
                                ^


TypeError: exports.serialize is not a function
    at Object.exports.log (<XXXX>\node_modules\winston-compat\index.js:205:33)
    at DailyRotateFile.log (<XXXX>\node_modules\winston-daily-rotate-file\daily-rotate-file.js:109:29)
    at transportLog (<XXXX>\node_modules\winston\lib\winston\logger.js:234:15)
    at <XXXX>\node_modules\async\lib\async.js:157:13
    at _each (<XXXX>\node_modules\async\lib\async.js:57:9)
    at Object.async.each (<XXXX>\node_modules\async\lib\async.js:156:9)
    at Logger.log (<XXXX>\node_modules\winston\lib\winston\logger.js:246:9)
    at target.(anonymous function) [as info] (<XXXX>\node_modules\winston\lib\winston\common.js:54:18)
    at Object.<anonymous> (<XXXX>\log.js:28:8)
    at Module._compile (module.js:570:32)
```

if I install the winston-compat dependency from github it works correctly (it seems their latest commit [0a6c478](https://github.com/winstonjs/winston-compat/commit/0a6c4781aab5e61ff9e6498062803a0f20b3ff0c) fixed this issue). However, the latest version published on npm (0.0.1) is behind.

A possible fix is to update package.json to use instead:
```
"winston-compat": "git+https://github.com/winstonjs/winston-compat.git#0a6c478"
```

**Comment by raghughagar** [comment]
const logger = new winston.Logger({
    level: 'verbose',
    transports: [
        new winston.transports.DailyRotateFile({
            filename: '%DATE%.log',
            datePattern: 'DD-MM-YYYY',
            prepend: true,
            level: 'verbose',
            maxDays: 0
        }),
        new winston.transports.Console({
            timestamp: true,
            colorize: true
        })
    ]
});

getting the same exception for this config. as well

**Comment by grofit** [comment]
Get this issue too

**Comment by mattberther** [comment]
I have been unable to have success getting the github version incorporated into `package.json`. It installs fine, until I install `winston@next`, at which point it removes it. I'll continue looking at that to see if we can publish an interim version.

Meanwhile, I've logged an issue at https://github.com/winstonjs/winston-compat/issues/2 to get a new version pushed to npm.

**Comment by shravan-shandilya** [comment]
@lpfeup's workaround works fine. But, Its better if the fix is released on **npm**.

**Comment by mattberther** [comment]
New version of `winston-compat` published to npm. Updated this project to reference `winston-compat@0.1.0` and published to npm. Should be resolved with `npm install winston-daily-rotate-file@3.0.1`.
