### ISSUE TITLE
Limit the total logs files size

### ISSUE THREAD

**Issue by sGambolati** [winstonjs/winston-daily-rotate-file#124]
Hi,
It is possible to limit the total size of the Logs? 
I know that there is a MaxDays and MaxSize properties. Besides that properties, I want to limit the total overall generated files to a given size (i.e. 1 GB). 

Thanks.

**Comment by nahuel** [comment]
Why this issue was closed? Is an useful feature, and is present in other libraries (see `totalSize` in  https://github.com/Rcomian/bunyan-rotating-file-stream )
