### ISSUE TITLE
Could not remove old log file

### ISSUE THREAD

**Issue by CnApTaK** [winstonjs/winston-daily-rotate-file#125]
```
const winston = require('winston');
require('winston-daily-rotate-file');

const transport = new (winston.transports.DailyRotateFile)({
	"name": "basic-log",
	"datePattern": "YYYY-MM-DD",
	"zippedArchive": false,
	"level": "info",
	"colorize": false,
	"filename": "./logs/log-%DATE%.txt",
	"maxSize": "1m",
	"maxFiles": "10",
});

transport.on('rotate', function(oldFilename, newFilename) {
	// do something fun
	console.log(new Date(), oldFilename, newFilename)
});

const logger = new (winston.Logger)({
	transports: [
		transport
	]
});

const str = 'Hello World! Hello World! Hello World! Hello World! Hello World! Hello World! Hello World! Hello World! Hello World! Hello World! Hello World! Hello World! Hello World! Hello World! Hello World! Hello World! Hello World!';
setInterval(function () {
	for (let i = 0; i < 100; i++)
		logger.info(str);
}, 10);
```
2018-03-20T12:44:14.690Z 'logs\\log-2018-03-20.txt.4' 'logs\\log-2018-03-20.txt.5'
2018-03-20T12:44:15.368Z 'logs\\log-2018-03-20.txt.5' 'logs\\log-2018-03-20.txt.6'
2018-03-20T12:44:16.067Z 'logs\\log-2018-03-20.txt.6' 'logs\\log-2018-03-20.txt.7'
2018-03-20T12:44:16.751Z 'logs\\log-2018-03-20.txt.7' 'logs\\log-2018-03-20.txt.8'
2018-03-20T12:44:17.468Z 'logs\\log-2018-03-20.txt.8' 'logs\\log-2018-03-20.txt.9'
2018-03-20T12:44:18.190Z 'logs\\log-2018-03-20.txt.9' 'logs\\log-2018-03-20.txt.10'
2018-03-20T12:44:18.869Z 'logs\\log-2018-03-20.txt.10' 'logs\\log-2018-03-20.txt.11'
2018-03-20T12:44:19.590Z 'logs\\log-2018-03-20.txt.11' 'logs\\log-2018-03-20.txt.12'
2018-03-20T12:44:20.270Z 'logs\\log-2018-03-20.txt.12' 'logs\\log-2018-03-20.txt.13'
2018-03-20T12:44:20.968Z 'logs\\log-2018-03-20.txt.13' 'logs\\log-2018-03-20.txt.14'
2018-03-20T12:44:20.968Z '[FileStreamRotator] Could not remove old log file: ' 'logs\\log-2018-03-20.txt.4'
2018-03-20T12:44:21.689Z 'logs\\log-2018-03-20.txt.14' 'logs\\log-2018-03-20.txt.15'
2018-03-20T12:44:22.369Z 'logs\\log-2018-03-20.txt.15' 'logs\\log-2018-03-20.txt.16'
2018-03-20T12:44:23.069Z 'logs\\log-2018-03-20.txt.16' 'logs\\log-2018-03-20.txt.17'
2018-03-20T12:44:23.790Z 'logs\\log-2018-03-20.txt.17' 'logs\\log-2018-03-20.txt.18'
2018-03-20T12:44:24.469Z 'logs\\log-2018-03-20.txt.18' 'logs\\log-2018-03-20.txt.19'
2018-03-20T12:44:25.170Z 'logs\\log-2018-03-20.txt.19' 'logs\\log-2018-03-20.txt.20'
2018-03-20T12:44:25.870Z 'logs\\log-2018-03-20.txt.20' 'logs\\log-2018-03-20.txt.21'
2018-03-20T12:44:26.570Z '[FileStreamRotator] Could not remove old log file: ' 'logs\\log-2018-03-20.txt.12'
2018-03-20T12:44:26.570Z 'logs\\log-2018-03-20.txt.21' 'logs\\log-2018-03-20.txt.22'
2018-03-20T12:44:27.282Z 'logs\\log-2018-03-20.txt.22' 'logs\\log-2018-03-20.txt.23'

and with "zippedArchive": true no file is deleted

**Comment by lpfeup** [comment]
your example works correctly for me with `"zippedArchive": false` (Windows machine).

But with `"zippedArchive": true`, old files do not get deleted:


```
2018-03-20T16:39:14.970Z '[FileStreamRotator] Could not remove old log file: ' 'logs\\log-2018-03-20.txt.2' 
```` 

Stack trace from [FileStreamRotator.js](https://github.com/rogerc/file-stream-rotator/blob/master/FileStreamRotator.js)
```
Error: ENOENT: no such file or directory, unlink '<XXXX>\logs\log-2018-03-20.txt.2'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:1103:18)
    at removeFile (<XXXX>\node_modules\file-stream-rotator\FileStreamRotator.js:258:16)
    at <XXXX>\node_modules\file-stream-rotator\FileStreamRotator.js:298:21
```

**Comment by mattberther** [comment]
Thank you for your report.

https://github.com/winstonjs/winston-daily-rotate-file/blob/8ad8579f1c6306a051518a48833337dc15a20ac1/daily-rotate-file.js#L86 already deletes the file after it's been zipped, as the assumption is upon zipping users will no longer wish to have the original file there. I'll submit a PR at FileStreamRotator.js to ignore errors on deleting.

**Comment by CnApTaK** [comment]
@lpfeup maybe because i restarting app few times and i saw it added to ".audit.json" same log file name multiple times

**Comment by mattberther** [comment]
@CnApTaK is the file removed, or is it not?

**Comment by CnApTaK** [comment]
with zippedArchive=true  - not removed

**Comment by mattberther** [comment]
I see. You mean the .zip files are not being removed, correct?

**Comment by CnApTaK** [comment]
yes

**Comment by mrwatson** [comment]
I'm seeing the same issue here. Error message is written to the console and it actually throws an unhandled error, which takes out the Node server. The *.log.gz files are definitely not being removed as expected.

**Comment by georgyngeorge** [comment]
I am seeing the same issues as well. the older *.gz files are not removed. The node server also crashes if exitOnError is not set to false.

**Comment by Acionyx** [comment]
Same error, but different behaviour. Seems like `audit.json` is not updated while files are deleted from disk.

**Comment by DSheffield** [comment]
I am seeing the same thing as @mrwatson. Deleting the log files fails and causes the whole nodejs server to crash.

**Comment by Acionyx** [comment]
@mattberther, any updates?

**Comment by esinyor** [comment]
Same issue, I think it's just that in FileStreamRotator.js on line 258, it doesn't check if zippedArchive is set to true

**Comment by monothorn** [comment]
@mattberther Any update on the resolution for this?

**Comment by mattberther** [comment]
I have some ideas on how to fix this. I hope to have some time to implement them shortly.

**Comment by chrisgel15** [comment]
@CnApTaK @Acionyx Regarding the audit.json file not updating correctly _(ie: multiple entries with the same file name)_ there's an issue with a dependency called File-Stream-Rotator (https://github.com/rogerc/file-stream-rotator) which is causing that behavior. There's a Pull Request open to fix it but it has not been integrated yet. (https://github.com/rogerc/file-stream-rotator/pull/37)

**Comment by mattberther** [comment]
Thanks @chrisgel15. Will monitor that request as well. This particular issue centers on the .gz file not being added to audit.json though. As a result, the .gz files are not being properly pruned.

**Comment by kicur** [comment]
Hi mattberther. Are you working on the fix for this issue ? I tested it and I think I found at least temporary solutions. If you add in FileStreamRotator.js in line 266 this part of code: 
else {
	const gzippedFileName = file.name + '.gz'
	if (fs.existsSync(gzippedFileName)) {
		fs.unlinkSync(fgzippedFileName);
	 }
}
gZipped files will be removed. It might be a temporary solutions or workaround but it not spoil anything so it might exist.

What do you think about add it to source code?

**Comment by rrpatilcse** [comment]
It works for me if `"maxFiles": "10"` set as `"maxFiles": 10`
But when I try with `"maxFiles": "1d"` i.e. to delete files before 1 day it's not working.

**Comment by dalelicious** [comment]
Same here. "maxFiles":  "1d" doesn't work in my end.

**Comment by dustingraham** [comment]
Just tested, the *.gz files are not being removed when it rolls over. I expect them to be removed, so there is a maximum of N-1 zips, and the current log, where N is the max files to keep.

**Comment by robsongajunior** [comment]
Yeah, **maxFiles** It is not working. \
I am using with the below config.

``` javascript
new (winston.transports.DailyRotateFile)({
        dirname: LOGDIR,
        filename: conf.file.log.access,
        zippedArchive: true,
        maxSize: '5m', // 5mb
        maxFiles: '2', // max 2 file
    })
```

and i have the respective files:

![screenshot to all gzip files not excluded](https://user-images.githubusercontent.com/3317013/57058510-c51de900-6c86-11e9-8acb-d50d88914073.png)

another case, it is generating the rotate files, but it is not clearing the main log file when move to another copy.

**Comment by Ben197** [comment]
Hi,
Regarding the logrotate:
This code works:

````
static logger = createLogger({
        level: config.get('logLevel'),
        format: format.combine(format.timestamp({format: 'YYYY-MM-DDTHH:mm:ss'}), format.json()),
        defaultMeta: { service: 'EHRM-KLANTNR'},
        transports: [
            new DailyRotateFile({
                filename: 'error-%DATE%.log',
                dirname: './logs',
                datePattern: 'YYYY-MM-DD-HH-mm',
                zippedArchive: false,
                level: 'error',
                maxFiles: '3',
                maxSize: '20m',
             }),
            new transports.Console,
            new transports.File({ filename: 'error.log'}),
           // new transports.File({ filename: 'errordebug.log', level: 'debug'})
        ]
    });
`````

In the code above, the files are deleted when the maxFiles is reached.

This code does not work:

````static logger = createLogger({
        level: config.get('logLevel'),
        format: format.combine(format.timestamp({format: 'YYYY-MM-DDTHH:mm:ss'}), format.json()),
        defaultMeta: { service: 'EHRM-KLANTNR'},
        transports: [
            new DailyRotateFile({
                filename: 'error-%DATE%.log',
                dirname: './logs',
                datePattern: 'YYYY-MM-DD-HH-mm',
                zippedArchive: true,
                level: 'error',
                maxFiles: '3',
                maxSize: '20m',
            }),
            new transports.Console,
            new transports.File({ filename: 'error.log'}),
           // new transports.File({ filename: 'errordebug.log', level: 'debug'})
        ]
    });
````

So when zippedArchive is set to true then the files are not deleted after the rotate.
I tried also options like  maxFiles: 3 and  maxFiles: '3m' 

I can live with that, but it should be nice when this is solved. :-)
Thanks

**Comment by theRealKhushal** [comment]
@mattberther Do we have any updates on this?

**Comment by Apollon77** [comment]
I also stumbled over this problem ... any solution on the horizon?

**Comment by mattberther** [comment]
Cherry-picked #260 at https://github.com/winstonjs/winston-daily-rotate-file/commit/e504c1385c1fc7bc7eb82511e182493b4b61fdc4. Published `winston-daily-rotate-file@4.4.1` which should resolve this issue.

**Comment by ym13349140** [comment]
@mattberther 
hi, I'm also facing the same question on v4.6.0. `maxFiles` can not remove new created log files.
My code are as follows:
```
const logger = function (options = {}) {
            return () => {
                const logDir = options.logDir || path.join(process.env.NODE_ENV !== 'production' ? process.cwd() : electronApp.getPath('userData'), 'logs');
    
                const transportList = [
                    new winston.transports.DailyRotateFile({
                        dirname: path.join(logDir, global.CONFIG.App.program_name),
                        filename: `${options.filename || options.name}-%DATE%.log`,
                        frequency: '1m',
                        datePattern: 'YYYY-MM-DD-HHmm',
                        maxSize: '1m',
                        maxFiles: 5,
                        createSymlink: false,
                        // symlinkName: `${options.symlinkName || options.name}.log`
                    }),
                ];
    
                if (process.env.CONSOLE_LOGGER) {
                    transportList.push(new winston.transports.Console);
                }
    
                return new winston.createLogger({
                    format: format.combine(
                        format.label({label: options.name}),
                        format.timestamp({format: "YYYY-MM-DD HH:mm:ss"}),
                        format.splat(),
                        format.simple(),
                        format.printf(({level, timestamp, message, label}) => {
                        //  const {tracert = {}, currentUser = {}} = options.currentContext || {};
                            return [`[${timestamp}]`, `[${level.toUpperCase()}]`, `[${label}]`].join(" ") + '^' + message
                        })
                    ),
                    level: 'debug',
                    transports: transportList
                })
            }
        };
```

everytime when I start running my application,once the total number of log files is over 5,  it can successfully remove the log files created before this setup, but cannot remove those log files created in this setup process, and get a "EPERM: operation not permitted". 
Can anybody help me?

**Comment by suruchi9837** [comment]
> It works for me if `"maxFiles": "10"` set as `"maxFiles": 10` But when I try with any other value it does not work
