### ISSUE TITLE
Winston not rotating log files auto everyday

### ISSUE THREAD

**Issue by NikhilBansal21** [winstonjs/winston-daily-rotate-file#126]
i have been implementing below mentioned code but logs are not being printed on daily basis in different log files (automatically)

var transport = new (winston.transports.DailyRotateFile)({
    filename: 'logs/ClientLogs-%DATE%.log',
    datePattern: 'YYYY-MM-DD-HH'
   
  });
var logger = new (winston.Logger)({
    transports: [
      transport
    ]
  });
it is making a new file only when i restart my node server.

**Comment by mattberther** [comment]
I am unable to reproduce this issue with the following code using `winston@2`.

```javascript
var winston = require('winston');
require('winston-daily-rotate-file');

var transport = new (winston.transports.DailyRotateFile)({
    filename: 'logs/ClientLogs-%DATE%.log',
    datePattern: 'YYYY-MM-DD-HH'
});

var logger = new (winston.Logger)({
    transports: [
        transport
    ]
});

logger.info('testing');

var time = new Date();
time.setTime(new Date().getTime() + (2 * 60 * 60 * 1000));
var tk = require('timekeeper');
tk.travel(time);

logger.info('testing');
```

The code creates 2 log files; one for the current hour and the other 2 hours ahead. If you continue to have this issue, please re-open with a more complete example replicating your problem.
