### ISSUE TITLE
Logged message is not JSON based

### ISSUE THREAD

**Issue by betimer** [winstonjs/winston-daily-rotate-file#128]
Hi,

The daily rotate file works fine, however its format is different with normal transport.file which is json based:

Normal Transport File:
`{"level":"warn","message":"Email server is not ready, ignoring it","timestamp":"2018-03-28T06:02:46.531Z"}`
DailyRotateFile:
`2018-03-28T06:02:46.531Z - warn: Email server is not ready, ignoring it`

It seems Daily Rotate File was using same format as print in console.

Is it a bug or there is a setting that I do not know?

Thank you very much

**Comment by mattberther** [comment]
Use the JSON formatted with a time stamp

```javascript
new winston.transports.DailyRotateFile({
    ...
    format: winston.format.combine(
        winston.format.timestamp(),
        winston.format.json()
    )
})
```

**Comment by sachinB94** [comment]
@mattberther Thanks. But, is it not possible with winston 2.x.x. I can't really upgrade winston to v3. And, `winston.format` is only in v3.
