### ISSUE TITLE
does not create folders with more than one leve

### ISSUE THREAD

**Issue by spearmootz** [winstonjs/winston-daily-rotate-file#130]
if date pattern is `YYYY/MM/DD` it fails to create the folders

it gets the following error
 no such file or directory, mkdir 'somePath\logs\2018\04\02'

**Comment by mattberther** [comment]
I am unable to reproduce this issue with the following code:

```javascript
var transport = new (winston.transports.DailyRotateFile)({
    filename: 'logs/%DATE%.log',
    datePattern: 'YYYY/MM/DD'
});
```

If you continue to see an issue, please re-open this ticket with a small code sample demonstrating the problem.
