### ISSUE TITLE
filename counter was added to filename wrongly.

### ISSUE THREAD

**Issue by TomRed97** [winstonjs/winston-daily-rotate-file#132]
new (winston.transports.DailyRotateFile)({
                filename: 'lol%DATE%.log',
                datePattern: 'yyyy',
                zippedArchive: true,
                maxSize: '5k',
                maxFiles: '14d'
            })

after maxSize exceeds, second file is created but filename is lol2018.log.1 . It's wrong. How we can leave filename same, like lol.log ?

**Comment by mattberther** [comment]
This is currently working as designed. There is an open issue to support tailable at #23. Closing this issue and you can monitor the other issue for progress.
