### ISSUE TITLE
error when using with 3.0.0-rc4

### ISSUE THREAD

**Issue by ADumaine** [winstonjs/winston-daily-rotate-file#133]
npm ERR! peerinvalid The package winston@3.0.0-rc4 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer winston-daily-rotate-file@3.0.1 wants winston@^2 <= 3.0.0-rc3 || ^3

**Comment by mattberther** [comment]
Pushed new version as `npm install winston-daily-rotate-file@3.0.2`. This version supports up to `winston@3.0.0-rc9`.
