### ISSUE TITLE
File not found when zippedArchive is set to true

### ISSUE THREAD

**Issue by akashsaluja** [winstonjs/winston-daily-rotate-file#135]
We are facing a problem in insertion to log file. 

We rotate log every hour, where each hour a new log file is created and previous one is zipped. 
In case of heavy inserts, sometimes it happens that an insertion fails because the file it is trying to write to has already been already zipped which causes the application to crash. It happens at first few mili seconds of an hour. 
For example at 12:00:00:35 (35 is ms) the it is trying to write is of 11-12 bracket. 

I assume it is happening because whenever it is being decided in which file it should insert has a lag in insertion and deciding. 
For instance a log which is generated at 11:59:59:950 will try to write to 11-12 bracket log file, but when it reaches the disk say at 12:00:00:35 it doesn't find the file. 

Can we not prevent this from happening? And even if it happens how can we stop application to terminate?

**Comment by chak774** [comment]
I have similar issue too.

**Comment by akashsaluja** [comment]
@chak774 I found my issue is due to ENOENT issue discussed in https://github.com/winstonjs/winston/issues/800

**Comment by tannineo** [comment]
Same orz.

**Comment by mattberther** [comment]
@chak774 Can you confirm that your comments on this issue, #18, and #142 are all the same. Or are these all different issues?

**Comment by summer995** [comment]
Same problem. Any update?

**Comment by mattberther** [comment]
Closing this issue. Please follow progress at https://github.com/winstonjs/winston/issues/800

**Comment by mattberther** [comment]
I've identified a potential issue that may be causing this issue. Please see #156 for more information.

**Comment by mattberther** [comment]
Closed with #156.

**Comment by mattberther** [comment]
Merged #156 and published to npm as `winston-daily-rotate-file@3.3.1`
