### ISSUE TITLE
Invalid path or filename after upgrading to 3.1.0

### ISSUE THREAD

**Issue by KingDGrizzle** [winstonjs/winston-daily-rotate-file#137]
Hello!

We've recently upgraded to version 3.1.0 of your library, but we've started to run into an issue with invalid pathnames, something that didn't occur pre-update.

As it can be seen here, 

https://github.com/GilbertGobbels/GAwesomeBot/blob/98b835d7c436c65aec829e357c1b62f33ba08761/Internals/Console.js#L43

We're setting the path like so. Is it wrong? 

Thanks.

**Comment by mattberther** [comment]
Apologies for the regression. This should be resolved with https://github.com/winstonjs/winston-daily-rotate-file/commit/aa3bf83f90057af69e28f43c0a754a5a8283d60e. This has also been pushed to npm as `winston-daily-rotate-file@3.1.2`.

Please re-open if you continue to see issues.

**Comment by KingDGrizzle** [comment]
Fantastic! It works now. Thanks for the quick answer / fix. 😃
