### ISSUE TITLE
As long as i put directory, then will hit error

### ISSUE THREAD

**Issue by BryanL33** [winstonjs/winston-daily-rotate-file#138]
this.dirname = "logs"
this.filename = "NormalLogFile_%DATE%.log"
```

if (!isValidFileName(path.join(this.dirname, this.filename))) {
            throw new Error('Your path or filename contain an invalid character.');
        }
```

**Comment by creativeview** [comment]
I get the same issue when I provide a path.  If I roll back to 3.0.2 the problem goes away.

**Comment by mattberther** [comment]
Apologies for the regression. This should be resolved with https://github.com/winstonjs/winston-daily-rotate-file/commit/aa3bf83f90057af69e28f43c0a754a5a8283d60e. This has also been pushed to npm as `winston-daily-rotate-file@3.1.2`.

Please re-open if you continue to see issues.
