### ISSUE TITLE
Error: tried to log to old archived log file

### ISSUE THREAD

**Issue by chak774** [winstonjs/winston-daily-rotate-file#142]
The logger is trying to write to archived log file. Then it throw error: no such file or directory. Below are the example of how I use the logger:

**logger.js**

const init = () => {

//Create Log Directory First
const logDir = process.env.LOG_DIR_PATH; // directory path you want to set
if ( !fs.existsSync( logDir ) ) {
    // Create the directory if it does not exist
    console.log("Log directory does not existed. Created Log Directory: ", logDir);
    fs.mkdirSync( logDir );
}

//Create Logger
logger = new (winston.Logger)({
    level: 'info',
    transports: [
        new winston.transports.Console({
            timestamp: () => {return getNowString();},
            formatter: (options) => {return logFormatter(options)}
        }),
        new dailyRotateFile({
          name: 'combined-file',
          timestamp: () => {return getNowString();},
          formatter: (options) => {return logFormatter(options)},
          filename: logDir + 'combined.log',
          datePattern: 'yyyy-MM-dd.',
          prepend: true,
          level: 'info',
          zippedArchive: true
        }),
        new dailyRotateFile({
            name: 'error-file',
            timestamp: () => {return getNowString();},
            formatter: (options) => {return logFormatter(options)},
            filename: logDir + 'error.log',
            datePattern: 'yyyy-MM-dd.',
            prepend: true,
            level: 'error',
            zippedArchive: true
        })
    ]
module.exports = { get : () => logger, init : () => init(), };

**index.js**

//Initilize a Logger
const logger = require('./util//logger/logger').init();

**Other JS files to use the logger:**

const logger = require('../util//logger/logger').get();
logger.info('...')

**Comment by mattberther** [comment]
Closing this issue. Please follow progress at https://github.com/winstonjs/winston/issues/800 If you believe this is not the same issue, please re-open this issue.

**Comment by mattberther** [comment]
I've identified a potential issue that may be causing this issue. Please see #156 for more information.

**Comment by mattberther** [comment]
Closed with #156.
