### ISSUE TITLE
Transport still processes logs when not attached to a Winston instance

### ISSUE THREAD

**Issue by Murreey** [winstonjs/winston-daily-rotate-file#143]
I was trying to create a DailyRotateFile object that I could add or remove to a Winston logger as I needed it, but found that once you create the DailyRotateFile, it'll print your logs even if you never add it to winston. 

Here's an example:

```javascript
import * as winston from 'winston'
import * as DailyRotateFile from 'winston-daily-rotate-file'

const logger = winston.createLogger({
    transports: []
})

new DailyRotateFile({
    filename: '%DATE%.log',
    dirname: 'logs',
    maxFiles: '14d'
})

logger.info('message')
```

This still creates the date.log file with the message in it, even though winston prints `[winston] Attempt to write logs with no transports {"message":"message","level":"info"}`, and shouldn't do anything with the log.

I'm using Winston 3.0.0-rc5 so not sure if that might have something to do with it (and Node v9.11.1, latest).

Thanks.

**Comment by mattberther** [comment]
The transport stream is created in the constructor, which is why you see the file being created after instantiation. Are you suggesting that it not create the file until a log entry is actually written?

**Comment by Murreey** [comment]
Ah sorry, totally misunderstood what it was doing - had old log lines in that file and thought it was creating a new file each time. My bad!
