### ISSUE TITLE
datePattern uses UTC Timezone

### ISSUE THREAD

**Issue by ben182** [winstonjs/winston-daily-rotate-file#144]
Hey,
the datePattern uses UTC Timezone even if I set a localtime. I know that there are multiple issues with this topic but I dont find a current fix for this.

**Comment by mattberther** [comment]
Can you please provide some additional information, including the version of the transport you're using, as well as the configuration options?

**Comment by ben182** [comment]
I use the plugin in this way:
`let winston = require('winston');
require('winston-daily-rotate-file');

winston.level = 'debug';
winston.add(winston.transports.DailyRotateFile, {
    filename: './logs/%DATE%.log',
    datePattern: 'YYYY-MM-DD',
    zippedArchive: true,
    maxFiles: '14d',
});
exports.winston = winston;`

My linux server uses the timezone CEST (date = Sat Apr 28 11:01:22 CEST 2018)
But when I look into the generated log files the current log for 11am is 
`2018-04-28T09:00:31.569Z - debug: `
It uses UTC

**Comment by mattberther** [comment]
@ben182 `datePattern` is used to create the name of the file, and not the log entries themselves. If you want to have a custom timezone in the log item, you'll want to look at implementing a `format` property.

An example might be:

``` javascript
var logger = winston.createLogger({
    format: winston.format.combine(
        winston.format.timestamp({
            format: function () {
                return new Date().toString();
            }
        }),
        winston.format.json()
    ),
    transports: [
        new (winston.transports.DailyRotateFile)({
            filename: 'log-%DATE%.log',
            datePattern: 'YYYYMMDD'
        });
    ]
});
