### ISSUE TITLE
log file querying ignores multiple files

### ISSUE THREAD

**Issue by mattberther** [winstonjs/winston-daily-rotate-file#15]
> Originally reported by @Pleochism at https://github.com/winstonjs/winston/issues/234

When querying log files, and logs are set to rotate after a specific size is reached, all files prior to the current file are ignored. The app should attempt to find prior log files and include their results.

**Comment by LukasHechenberger** [comment]
Running into the same issue. Has someone found a workaround / fix yet?

**Comment by mattberther** [comment]
I have not been able to look at this one yet.

**Comment by jpAgendize** [comment]
Hello, I think it's the same issue. 
When I do queries only the current edited file is processed. 
Is it a bug or do i miss something?

**Comment by nzomedia** [comment]
i'm facing the same issue  actually. Did someone find a solution ?

**Comment by mattberther** [comment]
#89

**Comment by mattberther** [comment]
Resolved with https://github.com/winstonjs/winston-daily-rotate-file/commit/52c2bcb646c16573c5fad32e224027e3bbf29996 and pushed to npm as 1.6.0
