### ISSUE TITLE
file-stream-rotator@^0.2.1 is missing

### ISSUE THREAD

**Issue by aleybovich** [winstonjs/winston-daily-rotate-file#151]
I'm running `npm install winston-daily-rotate-file` and I get the error:

npm ERR! code E404
npm ERR! 404 Not Found: file-stream-rotator@^0.2.1

Reproducible on several machines across the office.

**Comment by ChrisAlderson** [comment]
`file-stream-rotator@0.2.1` does exists, [but `npm` is having issues at the moment](https://status.npmjs.org/). So I think this is the issue here.

**Comment by mattberther** [comment]
Closing this out as unable to reproduce
