### ISSUE TITLE
Node > 4

### ISSUE THREAD

**Issue by vbardales** [winstonjs/winston-daily-rotate-file#153]
Version 0.1.3 of winston-compat is no more compatible with node <= 4. Please fix winston-compat version, set it as peer dependency or raise node version requirement.

**Comment by mattberther** [comment]
`winston-daily-rotate-file` already specifies `"node": ">=6"`. 

Closing this issue here, and we'll continue progress over at https://github.com/winstonjs/winston-compat/issues/9
