### ISSUE TITLE
An useless log dir was created after calling new winston.transports.DailyRotateFile( options )

### ISSUE THREAD

**Issue by LvChengbin** [winstonjs/winston-daily-rotate-file#157]
```
new winston.transports.DailyRotateFile( {
    dailyrotate: true,
    filename: '/.../lib/modules/server/app/log/info-%DATE%.log',
    datePattern: 'YYYY-MM-DD',
    maxSize: '20m',
    maxFiles: '30d',
    level: 'info' }
} );
```
After calling the code above, an empty log dir would be created in `/.../lib/server/`.

**Comment by mattberther** [comment]
The directories are created when you instantiate the transport. If you're seeing different behaviour, please reopen this issue.

**Comment by LvChengbin** [comment]
but it's not created in a correct path, and log files will not be created in that dir.

**Comment by mattberther** [comment]
Can you please confirm that you're intending to do `/.../`? There seem to be at least two issues with that path definition. 1) The first / indicates the root folder, and 2) The ... is not a valid path specification. Perhaps you meant .., but in that case the first / makes the .. redundant. More likely, you meant `../lib/modules/server/app/log/info-%DATE%.log`.

If Im misunderstanding the issue, please respond. Thank you!

**Comment by LvChengbin** [comment]
Oh, I am so sorry, because the full path is too long, so I tried omitting some dirs in the path.
 The `...` means there are something has been omitted and I am sure that I am using correct path in my code.
I am really sorry for that stupid thing.

**Comment by mattberther** [comment]
Can you please provide the minimal code sample that replicates your issue?

**Comment by LvChengbin** [comment]
I tried to write a sample, but at last, I found out the reason. It isn't because of `winston-daily-rotate-file` it is because of the library `file-stream-rotator` that being used in `winston-daily-rotate-file`. It created a `.audit.json` file for recoding a map of log files, and because I copied the directories, the `.audit.json` hasn't been rebuilt, it still has the old path in it, so `file-stream-rotator` makes some useless directories in the old path.

Thank you for your patience.

**Comment by mdemblani** [comment]
Can this part of information be added in the Wiki. It would help. I was facing a similar issue where the `FileStreamRotator` returned a permission error to store logs at some obscure directory, since I was running the logger initially outside docker and then inside a docker container.
