### ISSUE TITLE
Winston 3 - "undefined" gets logged when formater returns falsey value

### ISSUE THREAD

**Issue by SirMcPotato** [winstonjs/winston-daily-rotate-file#158]
## Description :
According to https://github.com/winstonjs/winston#filtering-info-objects, if a formater return evaluates to `false` then the log is ignored.

This works great with Winston's core transports such as `Console` and `File` as shown below.
However, the `DailyRotateFile` transports doesn't skip the logs and instead logs `undefined` on a single line.

----

## Dependencies :
- **winston** : `^3.0.0-rc6`,
- **winston-daily-rotate-file** : `^3.2.1`

----

## Code snippet :
In the following code snippet, I've configured the following transports to log only `silly` and `debug` levels :
```js
const { createLogger, format, transports } = require('winston');
require("winston-daily-rotate-file");

/**
 * Filters logs by levels.
 * @param {string|string[]} level - String or array of allowed levels
 */
function levelsFilter(level) {
    return format(info => {
        if (typeof level === 'string') {
            if (info.level === level)
                return info;
        } else if (Array.isArray(level)) {
            if (level.includes(info.level))
                return info;
        }
        return false;
    })();
}

const logger = createLogger({
    transports: [
        // Console transport, for comparison
        new transports.Console({
            level: 'silly',
            format: format.combine(
                levelsFilter(["silly", "debug"]),
                format.timestamp({ format: 'YYYY-MM-DDTHH:mm:ss.sss' })
            ),
        }),
        // File transport, for comparison
        new transports.File({
            dirname: 'logs',
            filename: `myService-native.log`,
            level: 'silly',
            format: format.combine(
                levelsFilter(["silly", "debug"]),
                format.timestamp({ format: 'YYYY-MM-DDTHH:mm:ss.sss' })
            ),
        }),
        // DailyRotateFile transport, which logs `undefined` on falsey value.
        new transports.DailyRotateFile({
            dirname: 'logs',
            filename: `%DATE%-myService-debug.log`,
            maxFiles: '10d',
            zippedArchives: true,
            level: 'silly',
            format: format.combine(
                levelsFilter(["silly", "debug"]),
                format.timestamp({ format: 'YYYY-MM-DDTHH:mm:ss.sss' })
            ),
        })
    ]
})

// Log some things :
logger.debug("Debug log");
logger.info("Info log"); // Shouldn't be displayed
logger.error("Error log"); // Shouldn't be displayed
logger.silly("Silly log");
```

----

## Output
The `Console` transport logs :
```
{"message":"Debug log","level":"debug"}
{"message":"Silly log","level":"silly"}
```

The `File` transport logs _(`logs/myService-native.log`)_ :
```
{"message":"Debug log","level":"debug"}
{"message":"Silly log","level":"silly"}
```

The `DailyRotateFile` transport logs _(`logs/%DATE%-myService-debug.log`)_ :
```
{"message":"Debug log","level":"debug"}
undefined   // <-- ❌ Info Log, shouldn't be displayed
undefined   // <-- ❌ Error Log, shouldn't be displayed
{"message":"Silly log","level":"silly"}
```

The `DailyRotateFile` should have mimicked the ouput of the core `File` transport, but as you can see we got two `undefined` lines for our filtered logs level.

I'll try to fix this on my spare time, and eventually send a PR if I managed to fix it!

**Comment by mattberther** [comment]
It turns out this is an issue in winston core. You can track the issue at https://github.com/winstonjs/winston/issues/1371

**Comment by mattberther** [comment]
This has been resolved with https://github.com/winstonjs/winston-daily-rotate-file/commit/4a7540787aeb166e2455b7d606a7a7cc507d1dc8#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 and pushed to npm as `winston-daily-rotate-file@3.2.2`.
