### ISSUE TITLE
Is there a configuration for log rotation that allows you to name log files without.%random%?

### ISSUE THREAD

**Issue by nbuzzi** [winstonjs/winston-daily-rotate-file#161]
I've the follow configuration:

`	"logging": {
		"level": "info",
		"fileName": "Logs/logfile-%DATE%.log",
		"fileNameDatePattern": "YYYY-MM-DD",
		"maxFiles": "10",
		"maxSize": "1k"
	}`

So, when the framework generates all the logs files it start to generates files with .1 .2, .3 sequentially.
Finally, I don't see any log with the .log extension, only `logfile-2018-06-29.1`,  `logfile-2018-06-29.2`,  `logfile-2018-06-29.3` and more.

Regards.

**Comment by mattberther** [comment]
Currently, when the rotation happens, the new file name is incremented. Tailable functionality has been requested at #23. Closing this and you can track progress there.
