### ISSUE TITLE
How to fire rotatelog event for testing

### ISSUE THREAD

**Issue by SridharRamasami** [winstonjs/winston-daily-rotate-file#167]
Hi,
Im using winston 3 and winston.transports.DailyRotateFile

I have code that pushes the log files to a main server when they are rotated, but there seems to be a bug somewhere in my code.  Currenlty I have to wait for midnight for the log rotate to occur to see if it went ok.  

For testing how can I fire a rotate event so that I can see if its behaving the way it should?

Thanks.

**Comment by mattberther** [comment]
Perhaps you're looking for the `emit` method.

``` javascript
var transport = new (winston.transports.DailyRotateFile)({
    dirname: 'logs',
    filename: 'log-%DATE%.log',
    datePattern: 'YYYYMMDD',
    zippedArchive: true
});

transport.on('rotate', function(old, newFile) {
    console.log('in rotate', old, newFile);
});

transport.emit('rotate', 'old', 'new');
```

Please re-open if this does not address your question.
