### ISSUE TITLE
Failing when starting my app

### ISSUE THREAD

**Issue by platinumgray** [winstonjs/winston-daily-rotate-file#168]
Hello, i recently start having this error, when my app starting

`TypeError: Cannot read property '1' of null
    at Object.FileStreamRotator.getStream (/var/www/html/app/node_modules/winston-daily-rotate-file/node_modules/file-stream-rotator/FileStreamRotator.js:396:38)
    at new DailyRotateFile (/var/www/html/app/node_modules/winston-daily-rotate-file/daily-rotate-file.js:81:57)`

dependencies from package.json
`"winston": "^3.0.0-rc6",
    "winston-daily-rotate-file": "^3.2.1",
    "winston-transport": "^4.2.0"`

**Comment by ritesh0919** [comment]
I also faced this issue and looks like defect introduced in file-stream-rotator v0.3.0. However v0.2.1 of the same package works perfectly. 

winston-daily-rotate-file latest release is dependent upon file-stream-rotator 0.3.0 and hence this issue. 

For now, to fix this issue, in my package.json, I have hard wired winston-daily-file-rotate to 3.1.3, it works file. This version depends upon 0.2.1 of file-stream-rotator, which works fine. You can try removing "^" from version 3.2.1 and check. If that does not work, then use version 3.1.3 without ^

Hope this helps...

**Comment by mattberther** [comment]
Please provide the configuration you're using to initialize the transport. All the unit tests pass, so if there's something strange going on here, I'd like to capture the behavior in a new test.

Thank you.

**Comment by ritesh0919** [comment]
Here is my configuration of transport definition:

```
const transports = {
	console: new Winston.transports.Console(),
	file: new Winston.transports.DailyRotateFile({
		dirname: dirname,
                filename: filename,
		zippedArchive: true,
		maxFiles: '10d',
		maxFiles: maxFiles,
		maxSize: fileSize,
                prepend: true
	})
};
```

Above dirname, filename, maxFiles and fileSize comes from my properties file. 

Let me point out another thing, the issue lies with the maxSize. If i remove that, it works. I tried debugging and reached to FileStreamRotator.js (of file-stream-rotator package), line 396. 

`fileCount = lastCount[1];`

In above code, lastCount is null and hence we see that error. 

Another observation, when I delete .audit.json, it works. Since it gets generated everything, it starts failing next time onwards.

**Comment by mattberther** [comment]
I'm unable to duplicate the issue using this code:

``` javascript
var winston = require('winston');
var randomString = require('./test/random-string.js');
require('winston-daily-rotate-file');

var logger = winston.createLogger({
    transports: [
        new (winston.transports.DailyRotateFile)({
            dirname: 'logs',
            filename: 'log-%DATE%.log',
            maxSize: '1k',
            maxFiles: 5
        })
    ]
});

for (var i = 0; i < 15000; i++) {
    logger.info(randomString(842));
}
```

**Comment by ritesh0919** [comment]
I am able to reproduce with the above configuration. I created a file called logger.js, did npm install of winston and winston-daily-rotate-file and then ran the logger.js using node.

I could see the issue when i run logger.js for the second time. Please note, the program starts properly for the first time but any subsequent run will result in failure.

**Comment by mattberther** [comment]
@ritesh0919 Still unable to reproduce. Can you provide additional details such as OS and node version, please?

**Comment by mattberther** [comment]
Thank you for the help. I've updated dependency and push `winston-daily-rotate-file@3.3.2` to npm.
