### ISSUE TITLE
"maxsize" and "maxSize" is confused in your code

### ISSUE THREAD

**Issue by fengxinming** [winstonjs/winston-daily-rotate-file#171]
`maxSize` is different from `winston.transports.File.options.maxsize`

67    if (options.stream) {
68        throwIf('stream', 'filename', 'maxsize');
69        this.logStream = new PassThrough();
70        this.logStream.pipe(options.stream);
71    } else {

81        this.logStream = require('file-stream-rotator').getStream({
82            filename: path.join(this.dirname, this.filename),
83            frequency: 'custom',
84            date_format: options.datePattern ? options.datePattern : 'YYYY-MM-DD',
85            verbose: false,
86            size: getMaxSize(options.maxSize),
87            max_logs: options.maxFiles,
88            end_stream: true
89        });

**Comment by mattberther** [comment]
They are two different transports. `winston-daily-rotate-file` uses `maxSize`.
