### ISSUE TITLE
Skip rotation when min size limit not reached. 

### ISSUE THREAD

**Issue by vishalgarale** [winstonjs/winston-daily-rotate-file#176]
Is there is an option to rotate and zip only if min size reached?

Below is the configuration we used.

```
var transactionTransport = new (winston.transports.DailyRotateFile)({
    filename: __dirname+'/../logs/transaction_-%DATE%_'+worker+'.log',
    datePattern: 'YYYY-MM-DD-HH',
    zippedArchive: true,
    maxSize: '10m',
});
```

**Comment by mattberther** [comment]
@vishalgarale I have not tried this, but I believe the following configuration should work:

```javascript
var transactionTransport = new (winston.transports.DailyRotateFile)({
    filename: __dirname+'/../logs/transaction_'+worker+'.log',
    datePattern: '',
    zippedArchive: true,
    maxSize: '10m',
});
```
Please let me know.

**Comment by vishalgarale** [comment]
@mattberther I want rotation when any one below condition is true

1. Max size reached
2. Time interval reached and file size > min size 

In given to your example, it will rotate only when 10m gets reached, not based upon particular interval.

**Comment by mattberther** [comment]
That is correct. That was the question in the OP. If you want the behaviour described above, Im sorry to say that the transport does not support this currently.

**Comment by vishalgarale** [comment]
@mattberther Thanks. Any alternate standard way to achieve above mentioned conditions?

**Comment by mattberther** [comment]
It will rotate after an interval, even when a size is mentioned. Your second requirement above indicated both needed to be true (and). However, if that is supposed to read "or" then just use a date pattern and the maxSize.
