### ISSUE TITLE
app crash if oldfile not exist if zippedArchive is true

### ISSUE THREAD

**Issue by laizhenhai88** [winstonjs/winston-daily-rotate-file#179]
this.logStream.on('rotate', function (oldFile) {
                var gzip = zlib.createGzip();
                var inp = fs.createReadStream(oldFile);
                var out = fs.createWriteStream(oldFile + '.gz');
                inp.pipe(gzip).pipe(out).on('finish', function () {
                    fs.unlinkSync(oldFile);    //     here.........
                });
            });

fs.unlinkSync(oldFile)  will crash
eg.   create two logger and write to same log file with different format

**Comment by erosval** [comment]
it seems exactly the same problem reported before (#178)

**Comment by laizhenhai88** [comment]
> it seems exactly the same problem reported before (#178)

yes, which version of your node ?

**Comment by erosval** [comment]
8 LTS
