### ISSUE TITLE
TypeError: asyncWrite is not a function

### ISSUE THREAD

**Issue by philippefutureboy** [winstonjs/winston-daily-rotate-file#180]
**npm version:** 6.4.1
**node version:** 8.11.4 x64
**electron version:** 2.0.8
**winston version:** 3.0.0-rc2
**winston-daily-rotate-file version:** 3.3.2

**Bug or feature?** => Bug

winston-daily-rotate-file throws the following exception upon boot of the app:

<img width="558" alt="screen shot 2018-09-25 at 7 50 07 pm" src="https://user-images.githubusercontent.com/31741972/46049420-482cfe80-c0fc-11e8-89ff-0addb290dcc8.png">

And since this happens before I can use the logger in the app, that's pretty much all the info I get >.>

Configuration:

```
level: 'debug',
transports: [
      {
        level: 'error',
        filename: paths.logs('arthur-dataloader-error-%DATE%.log'),
        format: <custom format function>,
        datePattern: 'YYYY-MM-DD',
        zippedArchive: true,
        maxSize: '10m',
        maxFiles: '14d',
      },
      {
        filename: paths.logs('arthur-dataloader-%DATE%.log'),
        format: <custom format function>,
        datePattern: 'YYYY-MM-DD',
        zippedArchive: true,
        maxSize: '10m',
        maxFiles: '14d',
      },
    ],
```

where:

* `paths.logs` resolves to `%APPDATA%\<app name>\logs`
* `<custom format function>` resolves to a combination of format, timestamp, json or printf

**How do I know that the issue stems from `winston-daily-rotate-file`?**

It's the only change since the last commit :) + commenting the import and changing back the config to use `winston.transports.File` solves the issue.

Let me know if you need more info to solve the issue!

Cheers ✨

Phil

**Comment by mattberther** [comment]
I think this may have something to do with your combination of node and npm. https://npm.community/t/asyncwrite-is-not-a-function-at-node-10-3-0-and-npm-6-1-0/193

Can you try with an alternate, out-of-the-box version? If you continue to be able to reliably reproduce the error, please provide the smallest code example that replicates the issue, complete with version information and I'll look to resolve.

**Comment by philippefutureboy** [comment]
Hey @mattberther! Thanks for your answer. I'll give it a shot within the next week and let you know what's up.

**Comment by mattberther** [comment]
You're welcome. Sorry I was not more help at the moment.

**Comment by philippefutureboy** [comment]
Hey @mattberther! I didn't have the time to review this, and I'm leaving for three weeks, so I'll probably get back to this issue later in November when I'll be working on the electron part of our product again. I'll let you know what's up as soon as I get to work on it.

**Comment by mattberther** [comment]
Please reopen if you have a small code example that replicates the problem.
