### ISSUE TITLE
maxFiles: keeps only the latest modified files in a folder (multiple transports to same folder)

### ISSUE THREAD

**Issue by mahe-m** [winstonjs/winston-daily-rotate-file#181]
### environment:
- _`winston`: "^3.1.0"_
- _`node -v`: v10.8.0
- _Operating System?_ macOS
- _Language?_ TypeScript 2.6

### What is the problem? 
creating winston logger with multiple transporters into the same directory.
Now, setting maxFiles to 4 will keep only 4 files of latest updated in the folder.

### What do you expect to happen instead?
I expect to keep 4 maxFiles of serverLog and also 4 maxFiles of errorLog.

### Other information
I'm using this function to create transport options.

```
const createTransportOpts = (fileName, level) => ({
  filename: `${fileName}-%DATE%.log`,
  datePattern: 'DD-MM-YYYY',
  maxSize: '10m',
  level,
  maxFiles: 4,
`});
```

Creating logger with multiple transports,
```
const logger = createLogger({
  level: 'info',
  format: combine(
    DateTimeFormat,
    myFormat,
  ),
  transports: [
    new (transports.DailyRotateFile)(
      createTransportOpts(path.join('/logs/', 'error'), 'error'),
    ),
    new (transports.DailyRotateFile)(
      createTransportOpts(path.join('/logs/', 'server')),
    ),
  ],
});
```

**Comment by mattberther** [comment]
Updated to `file-stream-rotator@0.4.0` and published `winston-daily-rotate-file@3.3.5`.
