### ISSUE TITLE
JSON option isn't working

### ISSUE THREAD

**Issue by radarsu** [winstonjs/winston-daily-rotate-file#188]
Just as in title. I've set up `json: false` and it's not working. Checked code in repository and indeed `this.options.json` is never used.

**Comment by mattberther** [comment]
Please provide the entire configuration you are using, including versions of `winston` and `winston-daily-rotate-file`.

**Comment by radarsu** [comment]
```
    "winston": "^3.1.0",
    "winston-daily-rotate-file": "^3.3.3"
```

After further investigation I figured out that at winston 3+ json option is simply obsolete and I defined custom format instead.

```
// transports
const dailyRotateFileTransport = new WinstonDailyRotateFile({
    datePattern: `YYYY-MM-DD_HH;mm;ss`,
    dirname: radarsuAppRootPath.resolve(`data/logs`),
    filename: `%DATE%.log`,
    json: false,  <------ does nothing
    level,
    maxFiles: '1d',
    maxSize: '1m',
    handleExceptions: true,
});
```

**Comment by mattberther** [comment]
That unnecessary parameter is in place because `winston@2` supports it - and this transport is backwards compatible with that version.

Given your comments, I'll go head and close the issue. Thanks for reporting back.
