### ISSUE TITLE
How to change the filename pattern on log rotation?

### ISSUE THREAD

**Issue by PrasannaaSanthanam** [winstonjs/winston-daily-rotate-file#193]
I have a requirement to customize the filename that gets generated on log rotation. 
As of now, on rotation, the filename gets generated  as filename.log.num, but I would like to keep **.log as a the final extension** on rotation. 

for ex i want the filenames to be as below on rotation:
**app-local.1.log** instead of  **app-local.log.1**

Thanks in advance. 
Prasannaa Santhanam

**Comment by Jeff-Lewis** [comment]
Something like
```javascript
 transport.on('rotate', function(oldFilename, newFilename) {
    fs.rename(newFilename, newFilename.replace('1.log', 'log.1');
  });
```

**Comment by mattberther** [comment]
@Jeff-Lewis's suggestion would work, however, the logs would not be in the audit file and therefore would not be removed based on settings in the config.

**Comment by PrasannaaSanthanam** [comment]
Thanks @Jeff-Lewis & @mattberther,  is there a way to take care of the log cleanups/removals as well when we rename the fileName on rotation.

**Comment by mattberther** [comment]
No. Unfortunately not.
