### ISSUE TITLE
Part of the fix for "support different "maxFiles" settings for different "DailyRotateFile" instances" (Issue #172) has a negative side effect on the maxFiles cleanup when using a single "DailyRotateFile" instance and application instance related options.

### ISSUE THREAD

**Issue by jebbinBjss** [winstonjs/winston-daily-rotate-file#195]
**Summary** 
The change in PR https://github.com/winstonjs/winston-daily-rotate-file/pull/175 means that logs files are not deleted if your options change when your service restarts.

**Description**

My current configruation for the daily rotate file transport is as follows:
``` javascript
new DailyRotateFileTransport({
    name: 'dailyRotateFile',
    filename: `${serviceId}-%DATE%.log`,
    dirname: `/tmp/exampleservice/`,
    maxSize: '10k',
    maxFiles: '3',
  });
```
Where the serviceId id is a guid, generated on the service startup.

This is with version 3.5.0. 

The issue is as follows: 
When the service is operating normally, (with the settings above), the log files will be limited to 3. So, after a short period there will be 3 log files and an audit file with a name of format .optionHash-audit.json. 
This addition of the optionHash was introduced in PR: https://github.com/winstonjs/winston-daily-rotate-file/pull/175. As the service continues, the log files are rolled over and limited to 3 without issue.

However, when the service restarts, a new audit file is generated because the optionHash is different (The serviceId has changed). The logging, rotation and cleanup starts happening on a new set of files, but the original set of files are no longer touched, and will never be cleaned up by winston.

**Comment by mattberther** [comment]
This transport will not delete files that it is not certain it created. Since your config uses a runtime variable, this is going to be impossible to force while still maintaining a resolution for #172.
