### ISSUE TITLE
about docker and multiple service processes

### ISSUE THREAD

**Issue by jarone** [winstonjs/winston-daily-rotate-file#197]
Using docker to deploy multiple service processes（use pm2）, `maxSize` option does not take effect.（but it's working outside of docker）

```shell
// before unzip
506 Nov 16 07:02 access-2018-11-16-06.log.gz

// after unzip
1.8K Nov 16 07:38 access-2018-11-16-06.log
```

```javascript
const pid = process.pid
const dirPath += '/pid_' + pid + '_' + moment().format('YYYY_MM_DD')
const accessLogPath = dirPath + '/access-%DATE%.log'

const accessTransport = new (winston.transports.DailyRotateFile)({
  filename: accessLogPath,
  datePattern: 'YYYY-MM-DD-HH',
  zippedArchive: true,
  maxSize: '1g',
  maxFiles: '30d'
})
```

**Comment by mattberther** [comment]
Can you please provide some more information? What you're showing does (by your post) work outside of docker. Can you provide a simple Dockerfile that consistently replicates the issue you're seeing?

Thanks!

**Comment by mattberther** [comment]
Closing to non-response. If this continue to be an issue, please re-open and provide a small code sample that reproduces the problem.

**Comment by jarone** [comment]
Sorry, I didn't give feedback in time. 

This issue was misreported. 

In fact, I didn't understand the meaning of `datePattern` correctly. 

I think it was because the first time I saw `winston-daily-rotate-file`, I was confused by the `daily` in its name :)
