### ISSUE TITLE
datePattern forces new files to be created

### ISSUE THREAD

**Issue by theivanaguilar** [winstonjs/winston-daily-rotate-file#199]
Using the following configuration:

    return new (winston.transports.DailyRotateFile)({
        datePattern: 'YYYYMMDDHHMMSS',
        dirname,
        filename: '%DATE%.log',
        maxSize: '50m',
    });

Instead of waiting for the file to hit the '50m' limit, the transport creates multiple files:

    20181118231164.log
    20181118231164.log
    20181118231166.log

Is this the intended behavior?

You can test it with the following code:

    var winston = require('winston');
    require('winston-daily-rotate-file');

    var logger = winston.createLogger({
        transports: [
            new (winston.transports.DailyRotateFile)({
                datePattern: 'YYYYMMDDHHMMSS',
                filename: '%DATE%.log',
                maxSize: '50m',
            }),
        ],
    });

    let num = 200;

    while (num > 0) {
        logger.info(`${num}`);
        num--;
    }

**Comment by mattberther** [comment]
@theivanaguilar This configuration makes a new file every second regardless of the 50m maxSize setting. The maxSize setting comes into play if that is reached before there is a rotation (e.g., in your example you'd have to write more than 50m into the file in under 1 second).
