### ISSUE TITLE
List of PRs from winston

### ISSUE THREAD

**Issue by indexzero** [winstonjs/winston-daily-rotate-file#2]
There pull-requests were made on `winston` when `winston-daily-rotate-file` was part of `winston` itself. Now that it is its own stand-alone module we need to consider these PRs to land here. 

- [ ] [[fix] DailyRotateFile is now writing to the correct file.](https://github.com/winstonjs/winston/pull/505)
- [ ] [DailyRotateFile transport: availability to prepend formatted date to log name](https://github.com/winstonjs/winston/pull/585)
- [ ] [zippedArchive working with DailyRotateFile ](https://github.com/winstonjs/winston/pull/675)
- [ ] [Flush buffer again after first "flush" event in daily-rotate-file transport](https://github.com/winstonjs/winston/pull/690)

**Comment by mattberther** [comment]
@indexzero I believe Ive brought over the remaining pull requests. I think we can close this issue out now.
