### ISSUE TITLE
custom frequency (like x minutes) enhancement

### ISSUE THREAD

**Issue by kuddusic** [winstonjs/winston-daily-rotate-file#200]
Hello Matt,

First of all, many thanks for this beautiful module. 
I am using it for my logging server. I had needed custom intervals like 10 minutes. After searching solution and spending quite time, I cloned the repo and change line 84 from
`` 
 frequency: 'custom',
``
to: 
``
 frequency: options.frequency ? options.frequency: 'custom' ,
``
So it can benefit from file-stream-rotator's feature. It works as expected even under high load.

if you think it is good idea, you can update it. I hope it helps somebody.

Best Regards,
Kuddusi Ciftcibasi

**Comment by mattberther** [comment]
Thank you for the suggestion. Implemented and published as `winston-daily-rotate-file@3.6.0`.
