### ISSUE TITLE
PERM: operation not permitted, unlink error

### ISSUE THREAD

**Issue by rhafeez** [winstonjs/winston-daily-rotate-file#201]
getting following error while logging and crashing application,

```
EPERM: operation not permitted, unlink 'xxx'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:1103:18)
    at WriteStream.<anonymous> (xxx\node_modules\wins
ton-daily-rotate-file\daily-rotate-file.js:100:24)
    at emitNone (events.js:91:20)
    at WriteStream.emit (events.js:185:7)
    at finishMaybe (_stream_writable.js:512:14)
    at afterWrite (_stream_writable.js:386:3)
    at onwrite (_stream_writable.js:376:7)
    at WritableState.onwrite (_stream_writable.js:90:5)
    at fs.js:2151:5
    at FSReqWrap.wrapper [as oncomplete] (fs.js:748:5)
error Command failed with exit code 1.
```

we have version "3.3.0" of library and following configuration,

```
  const logTransport = new (winston.transports.DailyRotateFile)({
    timestamp: function() {
      return new Date().toLocaleString();
    },
    level: appConfig.log.level,
    dirname: appConfig.log.Location,
    filename: 'xxx.%DATE%.log',
    datePattern: 'YYYY-MM-DD',
    zippedArchive: true,
    maxSize: '50m',
    json: true,
    prettyPrint: true 
  });
```

Any pointer why this is happening?

**Comment by mattberther** [comment]
The error code would seem to indicate a permissions issue.

**Comment by rhafeez** [comment]
@mattberther  It happens intermittently not always. it does create files in the location. if this is permission issue then it would have not created any files there.  is that related to compress file? because this happened twice when it was creating compress file.

**Comment by mattberther** [comment]
Could you provide a small code sample that consistently replicates the issue? Thank you.

**Comment by mattberther** [comment]
Closing to non-response. If this continue to be an issue, please re-open and provide a small code sample that reproduces the problem.
