### ISSUE TITLE
Error: Algorithm "sha1" not supported. supported values: passthrough

### ISSUE THREAD

**Issue by bgdsh** [winstonjs/winston-daily-rotate-file#203]
when I am using this package under Node 8.12.0 together with Winston 3, it will throw an error like above.

After editing the code like this: https://github.com/bgdsh/winston-daily-rotate-file/commit/bb4d278314d538420847cdee1d5b1adf7bc4c0a7, it works.

Why not a PR?
I tried, but I didn't pass the CI testing. Anyone who knows the CI rules well can help to fix this.

**Comment by mattberther** [comment]
It would appear as though your system does not support sha1 hashing. Can you please provide the output of the following nodejs code from your system?

```javascript
var crypto = require('crypto');
var hashes = crypto.getHashes();
console.log(hashes);
```

Thanks.

**Comment by mattberther** [comment]
Also, the issue with the PR was that it failed in the linting - you can always run `npm test` locally to identify any issues with the build.

**Comment by bgdsh** [comment]
> It would appear as though your system does not support sha1 hashing. Can you please provide the output of the following nodejs code from your system?
> 
> ```js
> var crypto = require('crypto');
> var hashes = crypto.getHashes();
> console.log(hashes);
> ```
> 
> Thanks.

```bash
$ node
> var crypto = require('crypto');
undefined
> var hashes = crypto.getHashes();
undefined
> console.log(hashes);
[ 'DSA',
  'DSA-SHA',
  'DSA-SHA1',
  'DSA-SHA1-old',
  'RSA-MD4',
  'RSA-MD5',
  'RSA-MDC2',
  'RSA-RIPEMD160',
  'RSA-SHA',
  'RSA-SHA1',
  'RSA-SHA1-2',
  'RSA-SHA224',
  'RSA-SHA256',
  'RSA-SHA384',
  'RSA-SHA512',
  'dsaEncryption',
  'dsaWithSHA',
  'dsaWithSHA1',
  'dss1',
  'ecdsa-with-SHA1',
  'md4',
  'md4WithRSAEncryption',
  'md5',
  'md5WithRSAEncryption',
  'mdc2',
  'mdc2WithRSA',
  'ripemd',
  'ripemd160',
  'ripemd160WithRSA',
  'rmd160',
  'sha',
  'sha1',
  'sha1WithRSAEncryption',
  'sha224',
  'sha224WithRSAEncryption',
  'sha256',
  'sha256WithRSAEncryption',
  'sha384',
  'sha384WithRSAEncryption',
  'sha512',
  'sha512WithRSAEncryption',
  'shaWithRSAEncryption',
  'ssl2-md5',
  'ssl3-md5',
  'ssl3-sha1',
  'whirlpool' ]
undefined
```

**Comment by mattberther** [comment]
Well, this was not the expected result. Could you put together the smallest bit of code that consistently replicates the problem you're seeing?

**Comment by bgdsh** [comment]
> Well, this was not the expected result. Could you put together the smallest bit of code that consistently replicates the problem you're seeing?

Sure, I will do it.

**Comment by bgdsh** [comment]
@mattberther 
I am so sorry, I cannot reproduce the bug. I doubt it is an issue caused by the outdated babel in my project. When I write a demo in pure ES5 js, it works fine.
Thank you for your time.
I will close it now.
