### ISSUE TITLE
"frequency" option does not do anything

### ISSUE THREAD

**Issue by aabuhijleh** [winstonjs/winston-daily-rotate-file#210]
Hi,
As the title suggests, "frequency" doesn't work at all for me. For example, using the code below, logs won't rotate every 1 minute as they should and the 'rotate' event is never fired.

winston v3.2.1
winston-daily-rotate-file v3.6.0

```
const winston = require('winston');
const DailyRotateFile = require('winston-daily-rotate-file');

const fileTransport = new DailyRotateFile({
    frequency: '1m',
    dirname: './logs',
    filename: 'log-test.log',
    maxSize: '2m',
    maxFiles: '3'
});

fileTransport.on('rotate', (oldFilename, newFilename) => {
    console.log('rotate event', oldFilename, newFilename); // never fired
});

winston.configure({
    transports: [fileTransport]
});

setInterval(() => {
    winston.info(`${new Date().toISOString()} -- test message`);
}, 5000)
```

**Update:**

After looking at the code, the problem is that the default datePattern value this module is providing file-stream-rotator is "YYYY-MM-DD". The following code is from file-stream-rotator:

```
var newDate = this.getDate(frequencyMetaData,dateFormat);
if (newDate != curDate || (fileSize && curSize > fileSize)) {
  // this will never be reached because newDate and curDate both will be 2019-02-03
}
```

**Comment by mattberther** [comment]
Thanks. Yes, it seems as though you've uncovered the issue. If you want to do minute-based file rotations, you'll need to add a datePattern that includes minutes (e.g., `datePattern: 'YYYY-MM-DD-HHmm'`).

**Comment by cesc1802** [comment]
```
          new winston.transports.DailyRotateFile({
            dirname: config.logging.dir,
            filename: `${config.logging.level}-%DATE%.log`,
            datePattern: 'YYYY-MM-DD-HHmm',
            maxSize: '50m',
            frequency: '1m',
```
This is my config. but frequency still not working. Why ?

**Comment by mattberther** [comment]
In this case, `frequency` is the same as the `datePattern`. What is the use case here?

**Comment by paolodenti** [comment]
I confirm that the frequency option is not doing anything.
with or without datePattern, it does not work

**Comment by SANTHOSH-SJ** [comment]
# Failure case
This will rotate file for every second- here frequency fails when seconds is passed
```
new winston.transports.DailyRotateFile({
    filename: 'combined-%DATE%.log',
    level: 'error',
    datePattern: 'YYYY-MM-DD-HHmmss',
    frequency: '1m'
});
```

# Success case
This will rotate file for every 5 minutes . Here frequency works.

```
new winston.transports.DailyRotateFile({
    filename: 'combined-%DATE%.log',
    level: 'error',
    datePattern: 'YYYY-MM-DD-HHmm',
    frequency: '5m'
});
```

## Package version

```
"winston": "3.3.3",
"winston-daily-rotate-file": "4.5.5"

```

**Comment by sunilpoojari** [comment]
Hello All,

As per my understanding the below code should create new log files in every five minutes. Please let me know if my understanding is not correct.

new winston.transports.DailyRotateFile({
    filename: 'combined-%DATE%.log',
    level: 'error',
    datePattern: 'YYYY-MM-DD-HHmm',
    frequency: '5m'
});

When I am using the above mentioned code nothing is happening the logs are getting appended to the same log file and no new file is getting created.

Is there anything that I might be missing or should check?
