### ISSUE TITLE
Could you add audit_file option?

### ISSUE THREAD

**Issue by YegorPavlenko** [winstonjs/winston-daily-rotate-file#212]
Could you add audit_file name option like in file-stream-rotator?
For now we have weird long audit file name each time when server restart.

**Comment by mattberther** [comment]
Implemented with https://github.com/winstonjs/winston-daily-rotate-file/commit/ebd52acb1bb5732db0afdf8869b51155e205661c and published as `winston-daily-rotate-file@3.7.0`.
