### ISSUE TITLE
Why keep winston-compat instead of a major version bump?

### ISSUE THREAD

**Issue by danielgindi** [winstonjs/winston-daily-rotate-file#213]
This is just adding unused junk to the project.

It could also not be tree-shaked by `rollup` or `babel` because of the way it is loaded (and the internal `logform` module's dynamic loading).

**Comment by mattberther** [comment]
This is necessary to keep support for `winston@2`, which is still prevalent. Perhaps at some point we'll deprecate support, but until then, we have to keep winston-compat.
