### ISSUE TITLE
Unexpected token  in JSON at position 0

### ISSUE THREAD

**Issue by dbakuntsev** [winstonjs/winston-daily-rotate-file#214]
Summary:
`query()` fails with "Unexpected token  in JSON at position 0" when `zippedArchive: true`. It would appear that `query()` needs to decompress `.gz` file contents instead of attempting to read it verbatim in `utf-8` encoding.

Configuration:
```
const logger = winston.createLogger({
    level: 'debug',
    transports: [
        new (winston.transports.DailyRotateFile)({
            filename: 'app-%DATE%.log',
            zippedArchive: true,
            maxFiles: '7d',
            dirname: outputDir,
            format: format.combine(format.timestamp(), format.json()),
            json: true
        })
    ]
});
```

Query:
```
logger.query({
            from: new Date() - 24 * 60 * 60 * 1000,
            until: new Date(),
            limit: 100,
            start: 0,
            order: 'desc',
            fields: ['message', 'level', 'timestamp']
        }, (err, results) => {
            // ...
        });
```

Environment:
1. `winston-daily-rotate-file` npm package version `3.7.0`
2. The application was running on certain days over a period of time, and collected several log files:
app-2018-12-10.log.gz
app-2018-12-11.log.gz
app-2018-12-12.log.gz
app-2019-02-15.log
app-2019-02-20.log
app-2019-02-21.log
3. The unprintable character in the error message is the first byte of the GZip archive: 0x1F.

**Comment by mattberther** [comment]
Thanks for the report. Implemented with https://github.com/winstonjs/winston-daily-rotate-file/commit/9d01a47daacc922feaebb0fcd3c3a4ed04704507 and deployed to npm as `winston-daily-rotate-file@3.8.0`.
