### ISSUE TITLE
Emit event on zip

### ISSUE THREAD

**Issue by fdammassa** [winstonjs/winston-daily-rotate-file#215]
It would be useful to emit a new event once the old log file is zipped.

You could add a line like this
`self.emit('rotate-zipped', oldFile+'.gz')`

right below
https://github.com/winstonjs/winston-daily-rotate-file/blob/master/daily-rotate-file.js#L109

**Comment by mattberther** [comment]
Good suggestion. Implemented with https://github.com/winstonjs/winston-daily-rotate-file/commit/0f1ae73097990645e64ffdae0d3ec59f2515c8e4 and deployed to npm as `winston-daily-rotate-file@3.8.0`.
