### ISSUE TITLE
[Question] How is the rotate event triggered?

### ISSUE THREAD

**Issue by lonix1** [winstonjs/winston-daily-rotate-file#216]
What is the scenario that triggers rotation?

Is there some resource that acts as a timer, or background scheduling, or does it happen upon next log event?

**Comment by mattberther** [comment]
When the log event is sent, a check is made to determine whether or not to rotate the file. If the file needs to be rotated, it is. This is followed by the rotate event being raised and then ultimately the log being written.

Please let me know if you have further questions.

**Comment by lonix1** [comment]
Thanks!
