### ISSUE TITLE
[Question] Safe to reuse transport?

### ISSUE THREAD

**Issue by lonix1** [winstonjs/winston-daily-rotate-file#217]
In my app logging occurs in two ways:
- regular logging via `winston`
- logging of requests via `express-winston` middleware

In both cases I want to log to the same file. Is it "safe" to use the same `DailyRotateFile` transport in both loggers?

How is this typically done - any best practices to share?

**Comment by mattberther** [comment]
You should be able to create an instance of the transport and pass it to your `winston.createLogger` call and then pass the same instance to the `transports` array in the `expressWinston.logger` method.

Please let me know if you have further questions.
