### ISSUE TITLE
TypeScript definition doesn't export enough

### ISSUE THREAD

**Issue by lonix1** [winstonjs/winston-daily-rotate-file#218]
Right now it only exports the constructor, so we can create instances but we can't refer to them without instantiation - makes IoC and tests very messy / impossible.

It should export the `DailyRotateFileTransportInstance` and `DailyRotateFileTransportOptions` interfaces.

````typescript
export interface DailyRotateFileTransportOptions extends Transport.TransportStreamOptions {
//...
}

//and

export interface DailyRotateFileTransportInstance extends Transport {
//...
}
````

**Comment by mattberther** [comment]
@lonix1 Candidly, Im not very familiar with TypeScript, but I thought @Slessi  and others addressed this in https://github.com/winstonjs/winston-daily-rotate-file/pull/189. If not, could you propose additional changes for review by them in a PR?

Thank you.

**Comment by lonix1** [comment]
I've never written a definition file for public use, so unsure. I think the above is all that's needed, but maybe they can verify.

**Comment by Slessi** [comment]
@Ionix1 pretty sure u can do


```ts
import boobs from "winston-daily-rotate-file"

const foo: boobs.DailyRotateFileTransportOptions = {}
```
