### ISSUE TITLE
Get Initial Log File Name

### ISSUE THREAD

**Issue by jehugaleahsa** [winstonjs/winston-daily-rotate-file#219]
It would be nice if there was a way to get the log file name prior to the first `rotate` event firing. In our situation, we need to pass the log file to another process so both are using the same log file. Right now, we have to duplicate the logic for generating the log file name so we have it immediately.

I see file stream rotator emits a `new` event. I am not sure this is what you'd need to expose or not: https://github.com/rogerc/file-stream-rotator/blob/master/FileStreamRotator.js#L474

**Comment by mattberther** [comment]
Merged #220 and pushed to nom as `winston-daily-rotate-file@3.9.0`.
