### ISSUE TITLE
uncaughtException: ENOENT: no such file or directory, unlink 'logs/applicaion-info.2019-04-29-07.log

### ISSUE THREAD

**Issue by ihtml5** [winstonjs/winston-daily-rotate-file#222]
### 1. Background
I am using pm2 and winston-daily-rotate-file to manage applications and local logs, which is very easy to use. I recently found some cases that caused application exceptions when observing online logs.
### 2. Logs
{"error":{"errno":-2,"syscall":"unlink","code":"ENOENT","path":"logs/applicaion-info.2019-04-29-07.log"},"level":"error","message":"uncaughtException: ENOENT: no such file or directory, unlink 'logs/applicaion-info.2019-04-29-07.log'\nError: ENOENT: no such file or directory, unlink 'logs/applicaion-info.2019-04-29-07.log'\n    at Object.unlinkSync (fs.js:952:3)\n    at WriteStream.<anonymous> (node_modules/winston-daily-rotate-file/daily-rotate-file.js:109:24)\n    at WriteStream.emit (events.js:187:15)\n    at finishMaybe (_stream_writable.js:641:14)\n    at stream._final (_stream_writable.js:619:5)\n    at WriteStream._final (internal/fs/streams.js:264:3)\n

### 3. Related version
1.     "winston-daily-rotate-file": "^3.8.0"

**Comment by ihtml5** [comment]
https://github.com/winstonjs/winston-daily-rotate-file/blob/07df9212b231935a746335b90a536790bd97d51e/daily-rotate-file.js#L115

**Comment by mattberther** [comment]
I'm moving this issue to #226, which more accurately describes the problem (`winston-daily-rotate-file` does not work well with process managers).
