### ISSUE TITLE
How to flush log to disk?

### ISSUE THREAD

**Issue by ddorsett** [winstonjs/winston-daily-rotate-file#223]
Any idea on the best way to ensure that pending entries are flushed to the log files when using daily rotating files?

**Comment by mattberther** [comment]
The transport should already do this. Do you have a situation with reproducible steps that demonstrates this not happening?

**Comment by terrisgit** [comment]
I have found that if your program exits normally or because of an uncaught exception, the files usually get flushed.

But if you need to stop the process yourself, this is the only magic that works and must be called before process.exit():
```
const categories = ['tom', 'jerry'];
const promises = categories.map((category) => new Promise((resolve) => {
  const logger = winston.loggers.get(category);
  if (logger.writable) {
    logger.on('error', resolve).on('close', resolve).on('flush', () => logger.close()).end();
  } else {
    resolve();
  }
}));

// These promises don't reject
await Promise.all(promises);
```

**Comment by sluukkonen** [comment]
I noticed the same issue and managed to fix it locally by implementing the _final method in the Node Writable stream API.

```js
DailyRotateFile.prototype._final = function _final(callback) {
    var self = this;
    if (this.logStream) {
        this.logStream.once('finish', callback)
        this.logStream.end()
    } else {
        callback()
    }
};
```
