### ISSUE TITLE
TypeError: Cannot set property DailyRotateFile of #<Object> which has only a getter

### ISSUE THREAD

**Issue by arasan-augment** [winstonjs/winston-daily-rotate-file#224]
/var/www/html/Projects/smartie-server/node_modules/winston-daily-rotate-file/index.js:6
winston.transports.DailyRotateFile = DailyRotateFile;
                                   ^

TypeError: Cannot set property DailyRotateFile of #<Object> which has only a getter
    at Object.<anonymous> (/var/www/html/Projects/smartie-server/node_modules/winston-daily-rotate-file/index.js:6:36)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/html/Projects/smartie-server/node_modules/parse-server/lib/Adapters/Logger/WinstonLogger.js:17:54)
    at Module._compile (module.js:653:30)

**Comment by mattberther** [comment]
Can you please provide the code you're using to try to configure your logger?

**Comment by arasan-augment** [comment]
@mattberther I didn't used the logger anywhere in my project. I just installed winstonjs package in my project. I can't run the project after installed this package

**Comment by arasan-augment** [comment]
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.logger = undefined;
exports.configureLogger = configureLogger;
exports.addGroup = addGroup;

var _winston = require('winston');

var _winston2 = _interopRequireDefault(_winston);

var _fs = require('fs');

var _fs2 = _interopRequireDefault(_fs);

var _path = require('path');

var _path2 = _interopRequireDefault(_path);

var _winstonDailyRotateFile = require('winston-daily-rotate-file');

var _winstonDailyRotateFile2 = _interopRequireDefault(_winstonDailyRotateFile);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var LOGS_FOLDER = './logs/';

if (typeof process !== 'undefined' && process.env.NODE_ENV === 'test') {
  LOGS_FOLDER = './test_logs/';
}

var currentLogsFolder = LOGS_FOLDER;

function generateTransports(level) {
  var transports = [new _winstonDailyRotateFile2.default({
    filename: 'parse-server.info',
    dirname: currentLogsFolder,
    name: 'parse-server',
    level: level
  }), new _winstonDailyRotateFile2.default({
    filename: 'parse-server.err',
    dirname: currentLogsFolder,
    name: 'parse-server-error',
    level: 'error'
  })];
  if (!process.env.TESTING || process.env.VERBOSE) {
    transports = [new _winston2.default.transports.Console({
      colorize: true,
      level: level
    })].concat(transports);
  }
  return transports;
}

var logger = new _winston2.default.Logger();

function configureLogger(_ref) {
  var logsFolder = _ref.logsFolder;
  var _ref$level = _ref.level;
  var level = _ref$level === undefined ? _winston2.default.level : _ref$level;

  _winston2.default.level = level;
  logsFolder = logsFolder || currentLogsFolder;

  if (!_path2.default.isAbsolute(logsFolder)) {
    logsFolder = _path2.default.resolve(process.cwd(), logsFolder);
  }
  if (!_fs2.default.existsSync(logsFolder)) {
    _fs2.default.mkdirSync(logsFolder);
  }
  currentLogsFolder = logsFolder;

  logger.configure({
    transports: generateTransports(level)
  });
}

configureLogger({ logsFolder: LOGS_FOLDER });

function addGroup(groupName) {
  var level = _winston2.default.level;
  var transports = generateTransports().concat(new _winstonDailyRotateFile2.default({
    filename: groupName,
    dirname: currentLogsFolder,
    name: groupName,
    level: level
  }));

  _winston2.default.loggers.add(groupName, {
    transports: transports
  });
  return _winston2.default.loggers.get(groupName);

**Comment by mattberther** [comment]
I'm still not clear on the minimum code you write that reproduces the error. Can you please provide that (without pasting the other library's code)?

**Comment by mattberther** [comment]
It appears as though this is not likely a problem with the transport. If you continue to have issues, I'd encourage you to capture them at https://github.com/parse-community/parse-server.

**Comment by mgara** [comment]
I have this exact issue just by running

` require('winston-daily-rotate-file')`

**Comment by mattberther** [comment]
At https://github.com/winstonjs/winston-daily-rotate-file/blob/07df9212b231935a746335b90a536790bd97d51e/package.json#L32, there is a peer dependency on the project that requires winston < 2 or winston < 3. 

Does the issue resolve itself when you install a winston version (e.g., `npm install winston@3`)?

**Comment by mgara** [comment]
@mattberther  yes it worked when I added winston as a dependency to my project

**Comment by mattberther** [comment]
Thanks, @mgara. As this component is a plugin to `winston`, I assumed that it would already be installed. However, I'll consider making the documentation clearer in this regard.

**Comment by gukjoon** [comment]
For me, I'm seeing this error when I have a Project A that depends on Project B that then depends on both winston and winston-daily-rotate-file:
`Project A` => `Project B` => [`winston`, `winston-daily-rotate-file`]

If I add winston as a dependency to Project A, everything works fine, but otherwise I see the `Cannot set property...` error above.

Is this expected?

**Comment by gukjoon** [comment]
Ah on further examination, `Project A` also depends on `forever` which depends on `winston@0.8.5`. I think this is likely a similar issue other users are facing as well.

The problem is the state of node_modules
```
node_modules/
    forever
    project_b/
         node_modules/
             winston@3.x.x
    winston@0.8.5
    winston-daily-rotate-file
```

Very weird that it's hoisting `winston-daily-rotate-file`. Any way to stop this from happening?

**Comment by mattberther** [comment]
I can't comment on issues with `forever`. I'll admit the node_modules state you describe above is strange. I'd expect forever to also have a node_modules folder and `winston@0.8.5` be present in there.

Perhaps @indexzero could comment (as maintainer of both `winston` and `forever`).

**Comment by bizob2828** [comment]
@mattberther I'm facing the same issue as @gukjoon.  We develop a npm module that uses `winston-daily-rotate-file` and we specify `winston` 3 as a dep but when dependencies get resolved, if a customer is using winston < 2 it puts the winston 3.x in our node_modules not in the root howerver `winston-daily-rotate-file` gets installed at app root, thus causing the same issue.  I was hoping publishing a shrinkwrap would work but it looks like peer deps don't get tagged.  I'm not sure the best way to fix this
