### ISSUE TITLE
Rename files

### ISSUE THREAD

**Issue by Nesher123** [winstonjs/winston-daily-rotate-file#225]
Hi,
I'm having a problem modifying filenames.

Every time a new file is created, a number is appended to its end.
How can I manage it to have the extra numbers before the file extension?
i.e the filename is 'error.log' and when it reaches a certain size -> 'error.log.1' is created, but I would like to get 'error1.log' or 'error.1.log'

Thanks,
Ofir

**Comment by mattberther** [comment]
This is not currently possible. This is being tracked over at https://github.com/rogerc/file-stream-rotator/issues/48 and once that issue is resolved, the capability will be available here.

**Comment by mattberther** [comment]
Published `winston-daily-rotate-file@4.0.0` to resolve this issue.
