### ISSUE TITLE
Unable to set the frequency and disable audit logs in typescript

### ISSUE THREAD

**Issue by ayushsomani11** [winstonjs/winston-daily-rotate-file#227]
I am using "winston-daily-rotate-file": "3.9.0" in my application with typescript and i am unable to set frequency and disable audit.json file in my logs folder. Can someone help me with how can i disable  audit.json file and set frequency to delete my log files after every 5 days. I don't see frequency option for the object and auditFile as well. My code looks like below:-

```javascript
import * as DailyRotateFile from 'winston-daily-rotate-file';

const FileTransport = new DailyRotateFile({
            filename: `logs/%DATE%.log`,
            maxFiles: 1,
            format: Winston.format.combine(
                Winston.format.timestamp(),
                Winston.format.align(),
                Winston.format.printf((info) => {
                    const {timestamp, level, message, ...args} = info;
                    const ts = timestamp.slice(0, 19).replace('T', ' ');
                    return `${ts} ${level}:${message} ${
                        Object.keys(args).length ? JSON.stringify(args, null, 2) : ''
                        }`;
                })
            ),
           
          });

        return Winston.createLogger({
            transports: [FileTransport, consoleTransport]
        });
    }
}

**Comment by mattberther** [comment]
Why do you want to disable audit.json? As far as retaining files for five days, I think you want to set `maxFiles: 5` with your code above.

**Comment by ayushsomani11** [comment]
i not looking forward to generating audit.json file every time a new file is created in my production system. IS there any way to disable that?, also i set maxFiles to 1 and see it generated a new file every day. Do we need to specify same file name to achive this?

**Comment by mattberther** [comment]
The audit.json file is used to determine what files to purge and therefore is considered a necessary piece of this transport. If you would rather not have rotating files, perhaps you want to look at `winston.transports.File`.

**Comment by ayushsomani11** [comment]
ok,  if that is the case then i would have to switch to log4js from winston. But in future may be if possible rather than a different file with a very unfriendly name we can append date at end of last file when new file is generated or may be we can add one line comment at top while creating any log file and purge from reading the comment. Thanks for the support Matt!
