### ISSUE TITLE
Change the number of maxFiles (DailyRotateFile) at runtime

### ISSUE THREAD

**Issue by parthgoyal** [winstonjs/winston-daily-rotate-file#228]
Hi Matt,

Can we change the number of maxFiles (DailyRotateFile) at runtime?

I created the winston logger as follows:

const { createLogger, format, transports } = require('winston');
const { combine, timestamp, label, printf, splat } = format;
require('winston-daily-rotate-file');

const myFormat = printf(({ level, message, label, timestamp }) => {
return ${timestamp} [${label}] ${level}: ${message};
});

var transport = new (transports.DailyRotateFile)({
filename: path.join(PATH , 'log_%DATE%.log'),
datePattern: 'YYYYMMDD',
zippedArchive: false,
maxFiles: '7'
});

const logger = createLogger({
level: "debug",
format: combine(
label({ label: process.pid }),
timestamp({format: 'YYYY-MM-DD HH:mm:ss'}),
splat(),
myFormat
),
transports: [ transport
]
});

Now I am trying to change the maxFiles as follows:

logger.transports[0].options.maxFiles= <user_input>

But this is not working. Please suggest the way to do the same.
Thanks

**Comment by mattberther** [comment]
I don't understand the use case here. Could this be satisfied by recreating the transport with the maxFiles value you desire?

**Comment by parthgoyal** [comment]
**Use Case is like this:**

My application is Client-Server Application. Now in client, I am using winston logger to log activity of client. The maximum number of log files that has to be maintained is based on policy, which is sent by server (server will send this number).  Now the point is this number (maxFiles) can vary over period of time, for example, today server sent maxFiles = 5, tomorrow it can send maxFiles=8. 

**Could this be satisfied by recreating the transport with the maxFiles value you desire?**

Currently, I am using like this only. However, I have to make some compromises in the application

Thanks

**Comment by mattberther** [comment]
What are the compromises in the application?

**Comment by mattberther** [comment]
Workaround in place. Please reopen if you can provide additional details for this use case.

**Comment by ankurkapil8** [comment]
@mattberther 
How to pass dynamic value of "maxSize" like below

logger.transports[0].options.maxFiles= <user_input>

**Comment by mattberther** [comment]
@ankurkapil8 This is not currently supported and there are no plans on supporting it. A workaround is in place, which is to recreate the transport as needed.
