### ISSUE TITLE
Daily rotator transport doesn't seem to respect tailable

### ISSUE THREAD

**Issue by mattberther** [winstonjs/winston-daily-rotate-file#23]
> Originally reported by @alonisser at https://github.com/winstonjs/winston/issues/589

The docs state that : "In addition to the options accepted by the File transport..." So I assumed it would respect tailable (meaning it would always log to the same file, and rotate with date the older/maxsized files). But I succeed in making it work (or locating in daily rotator transport code exactly where would it actually respect tailable.

Is there a way to make this work?

**Comment by rootical** [comment]
Any news on that? Can't make it working :(

**Comment by WegDamit** [comment]
Ping.

It would be nice to have only one file to tail, like bla.log and have its content rotated to bla-yy.mm.dd.log (or whatever)
Now the used log file is already named bla-<today>.log.
Makes it harder to ind the actual log fail for e.g. monitoring...

**Comment by AlexGue** [comment]
Any updates about this?

When I set (maxFiles: '3d') for example, and set maxSize option, it creates files a new file without deleting old ones every time the maxSize is reached.

I want to add the date to log filenames and take care about max number of files, to limit the total size of all log files together, but I didn't make it work.

**Comment by mattberther** [comment]
@AlexGue which version of the transport are you using? If you're using the 2.x RC, please continue the conversation over at #107.

**Comment by cronon** [comment]
still doesn't work with winston@2.4.1 and winston-daily-rotate-file@3.0.1
I tried following config
```
const logger = new winston.Logger({
    transports: [
      new winston.transports.DailyRotateFile({
        filename: 'drf.log',
        datePattern: 'HH-mm',
        maxFiles: 3,
        maxSize: 200,
        tailable: true
      })
    ]
})
```
and saw files i.e. `drf.log.16-42` `drf.log.16-42.1` `drf.log.16-42.2` where `drf.log.16-42` contains the oldest logs

**Comment by mattberther** [comment]
This issue is still open, meaning tailable support does not currently work with this transport.

**Comment by FelixButzbach** [comment]
This would be really great to have. Any plans on looking into? Or is this something that needs to be done in the winston package?

**Comment by mattberther** [comment]
This is documented as an issue upstream at https://github.com/rogerc/file-stream-rotator/issues/44. I'll continue to monitor there and incorporate a new version that has this support, once available.

**Comment by rogerc** [comment]
@mattberther I've just published 0.5.0 with some enhancements/fixes. One of them is to include a symbolic link to the current active log file that can be accessed via current.log  The *current.log* file is in the same directory as the other logs.

**Comment by mattberther** [comment]
https://github.com/winstonjs/winston-daily-rotate-file/commit/090f7a9450b8ef130b3aafbd6dee036bc869b567 introduced `file-stream-rotator@0.5`, which adds a symlink to *current.log* which can be tailed.

There are a few other bug fixes to resolve before I push `winston-daily-rotate-file@4.0.0` to npm. I expect this to happen in the next day or two.

**Comment by sumeet-bansal** [comment]
@rogerc Is there any way to rename `current.log` to something else, e.g. `service.log`?

**Comment by rogerc** [comment]
@sumeet-bansal v.0.5.5 has the option to configure the name of the symbolic link. @mattberther also submitted a PR to enable symlink to not make it mandatory. Not sure if @mattberther needs to do anything to enable the winston transport with v0.5.5

**Comment by mattberther** [comment]
@sumeet-bansal Resolved with https://github.com/winstonjs/winston-daily-rotate-file/commit/31b1dc5018658f2b88fde6011f2a7db3221c19b7 and pushed as `winston-daily-rotate-file@4.1.0`.
