### ISSUE TITLE
Filename includes timezone offset. How to disable?

### ISSUE THREAD

**Issue by ifree92** [winstonjs/winston-daily-rotate-file#231]
I have faced with issue that the datePattern includes timezone offset. I would like to have the file names in UTC.

I'm using the next settings:

```js
export interface IWinstonFactoryOptions {
  prefix?: string;
  console?: boolean;
  path: string;
  maxFiles: number;
}

function loggerFormat(data: TransformableInfo): string {
  return `${data.timestamp} [${data.label || ''}] ${data.level}: ${(data.durationMs !== undefined
    ? `(${data.durationMs}ms) `
    : '') + data.message}`;
}

export function createWinstonLogger(opts: IWinstonFactoryOptions): Logger {
  const prefix = opts.prefix || 'log_';
  const console = opts.console || false;

  const logger = createLogger({
    exitOnError: false,
    level: 'silly',
  });

  logger.add(
    new DailyRotateFile({
      format: format.combine(format.timestamp(), format.printf(loggerFormat)),
      filename: `${prefix}%DATE%.log`,
      datePattern: 'YYYY-MM-DDTHH',
      zippedArchive: false,
      maxFiles: opts.maxFiles,
      dirname: opts.path,
    })
  );

  if (console) {
    logger.add(
      new transports.Console({
        format: format.combine(format.colorize(), format.timestamp(), format.printf(loggerFormat)),
      })
    );
  }

  return logger;
}
```

Especially please look here: `datePattern: 'YYYY-MM-DDTHH'`

In practice I have the file: `app_2019-07-24T22.log` where the first line is: `2019-07-24T19:05:26.185Z [label] ...`.
(I have +03 hours timezone)

Is that an issue or expected behaviour? I haven't found way to force to use file rotator only UTC for file names.

**Comment by mattberther** [comment]
This feature is being tracked at https://github.com/rogerc/file-stream-rotator/issues/31. Once this is supported by the file-stream-rotator component, I can publish a new version of winston to support the option.

**Comment by ifree92** [comment]
@mattberther
That would be great to have this option.
I'm using Winston with application which is rotating on raspberry devices, and each has personal timezone and it's a headache to have files not in UTC.
If you can, please, publish new version with ability to use UTC for file names.

Thank you

**Comment by mscottnelson** [comment]
@mattberther, file-stream-rotator has published an update enabling a UTC option. Additionally, a bug fix related to varying results depending on when file-stream-rotator evaluated has been fixed: https://github.com/rogerc/file-stream-rotator/issues/53

So, a UTC option should now be possible. Let me know if you would like a PR.

**Comment by mattberther** [comment]
Thanks for the offer, @mscottnelson. If you have a PR, I'd welcome it. :)

**Comment by IvayloB9** [comment]
Thank you for the quick turnaround! :)

**Comment by ifree92** [comment]
Just added PR for `utc` option on d.ts.
Would be great to have a new release asap :)
