### ISSUE TITLE
Store the Zip files under another folder during rotation

### ISSUE THREAD

**Issue by vigneshwaran-natarajan** [winstonjs/winston-daily-rotate-file#233]
Is it possible to store the zip under a file archive during log rotation?

Currently zip files are present on the same folder, is there any possible way to move the zip into the folder during rotation.

If there is any way , whether the `maxFiles`  will refer to that folder ? 

```
app-2019-08-08.log
app-2019-08-08.log.gz

--------
app-2019-08-08.log
archive/app-2019-08-08.log.gz

```

**Comment by mattberther** [comment]
You could likely listen for the `archive` event and move things around in that body:

```
transport.on('archive', function (filename) {
    // whatever you want to do in here
});
```

If you go this route, maxFiles will not look at that folder.
