### ISSUE TITLE
A new file is created when current file has not exceeded it's maxsize

### ISSUE THREAD

**Issue by martinrodland** [winstonjs/winston-daily-rotate-file#234]
I would like to only create a new file, when current file exceeds it's maxSize.
However it seems like when the `%DATE%` no longer applies to the current(meaning that the current date is different from the one when created), it will create a new file instead of using the current file.

for example:

if I create a file
`application-2019-07-19T05-12.log`
and the wait a few minutes it will create a new file, with the current time(`application-2019-07-19T05-15.log`) even though the first file is not full.

Config:

```
            level: 'info',
            filename: 'logs/application-%DATE%.log',
	        datePattern: 'YYYY-MM-DDTHH-mm',
            maxsize: 1k, // for testing
            maxFiles: 3,
	        audit: "logs/application-audit.json"
```

Is this the expected behavior or could my configs be wrong?

**Comment by mattberther** [comment]
This is working as expected. The primary criteria for rotation is the date pattern. The secondary criteria is the max size and max files.

I hope this makes things clearer.
