### ISSUE TITLE
%DATE% being appended to filename

### ISSUE THREAD

**Issue by sumeet-bansal** [winstonjs/winston-daily-rotate-file#235]
My current transport:
```typescript
new WinstonDailyRotateFile({
    dirname: "./var/log",
    filename: "service.log",
    datePattern: "YYYY-MM-DD",
    zippedArchive: true,
    maxSize: "1g",
    maxFiles: "30d",
}),
```

This writes logs to `./var/log/service.log.%DATE%`; how can I avoid this? Also, how can I specify a different directory for rotated logs?

**Comment by sumeet-bansal** [comment]
@mattberther?

**Comment by mattberther** [comment]
Your first question should be resolved with the following configuration:

```
filename: "service-%DATE%.log"
```

At this time, there is not a way to specify a different directory for rotated logs.

**Comment by sumeet-bansal** [comment]
Is there any way to have the primary log be called just service.log?

**Comment by mattberther** [comment]
Not at this time. You can track #23 for progress on that front.
