### ISSUE TITLE
this type declaration is still flawed

### ISSUE THREAD

**Issue by BubbleBear** [winstonjs/winston-daily-rotate-file#237]
only instance is exported while interface isn't, in which case the instance cannot be exported again.
besides the filename or stream argument must be provided, which isn't revealed in this option declaration.
and powered by declaration merging, it is even possible to access DailyRotateFile class from winston.tranports.

![image](https://user-images.githubusercontent.com/17879773/64397280-55d05f80-d093-11e9-87f6-c47b1e25e84d.png)
![image](https://user-images.githubusercontent.com/17879773/64397288-5e289a80-d093-11e9-901f-9253a582efed.png)

**Comment by BubbleBear** [comment]
i'm about to work on it.

**Comment by zieglar** [comment]
please fix this.

**Comment by mattberther** [comment]
Resolved with https://github.com/winstonjs/winston-daily-rotate-file/commit/57ffbd21265a106503f732b89b085826b3fc2249 and published to npm as `winston-daily-rotate-file@4.2.0`.
