### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by foaadnami** [winstonjs/winston-daily-rotate-file#241]
Changelog or notes with releases will only make this great project greater 

Thanks!

**Comment by CoolCyberBrain** [comment]
Just for those who are looking, there's the compare for v3.10.0 and v4.0.0 https://github.com/winstonjs/winston-daily-rotate-file/compare/v3.10.0...v4.0.0

**Comment by mattberther** [comment]
Noted. Thank you. I've added notes to https://github.com/winstonjs/winston-daily-rotate-file/releases/tag/v4.0.0 for this release and will endeavor to publish future release notes.
