### ISSUE TITLE
does not work on windows 10 with latest node version if running by user and user if folder owner and even have full control

### ISSUE THREAD

**Issue by CnApTaK** [winstonjs/winston-daily-rotate-file#243]
failing in fs.symlinkSync(logfileName, current) (line 297) in FileStreamRotator.js
saying: Error: EPERM: operation not permitted, symlink 'application-2019-09-09-15.log' -> 'logs/current.log'
this is the test code:
```const _winston = require('winston');
const { createLogger } = _winston;
require('winston-daily-rotate-file');
const transport = new (_winston.transports.DailyRotateFile)({
	filename: './logs/application-%DATE%.log',
	datePattern: 'YYYY-MM-DD-HH',
	zippedArchive: true,
	maxSize: '20m',
	maxFiles: '14d'
});
const log = createLogger();
log.add(transport);
log.info('test');
log.info('test');
log.info('test');
```
this code is working only under user with administrator role
probably node.js bug

strange.. under user role node can create folder.. log file in that folder but cannot create symlink on that file in same folder

**Comment by CnApTaK** [comment]
is there any option which disable creating symlink to current.log ?

**Comment by CnApTaK** [comment]
it seems symlinks in windows 10 for not admins is working only if windows is set to "developer mode"
so.. i guess you need to disable making symlink by default and put it into option flag... otherwise can't continue use this library (((

**Comment by mattberther** [comment]
A PR to support this option is at https://github.com/rogerc/file-stream-rotator/pull/58. As soon as it's merged there, I'll create a new version.

**Comment by mattberther** [comment]
Resolved with https://github.com/winstonjs/winston-daily-rotate-file/commit/31b1dc5018658f2b88fde6011f2a7db3221c19b7 and pushed as `winston-daily-rotate-file@4.1.0`.
