### ISSUE TITLE
process.nextTick is not a function

### ISSUE THREAD

**Issue by shukriadams** [winstonjs/winston-daily-rotate-file#244]
On version 1.7.2 (yes, I know it's old) I'm getting the following error
```
/vagrant/src/node_modules/winston-daily-rotate-file/index.js:514
    process.nextTick(function () {
            ^

TypeError: process.nextTick is not a function
    at /vagrant/src/node_modules/winston-daily-rotate-file/index.js:514:13
    at Array.forEach (<anonymous>)
    at module.exports.DailyRotateFile.flush (/vagrant/src/node_modules/winston-daily-rotate-file/index.js:510:16)
    at createAndFlush (/vagrant/src/node_modules/winston-daily-rotate-file/index.js:603:12)
    at /vagrant/src/node_modules/winston-daily-rotate-file/index.js:627:16
    at FSReqWrap.oncomplete (fs.js:153:21)
```
this seems to be caused by process being grabbed from the global namespace, instead of being explicitly required locally. This error occurs only in some of my projects, presumably some other module is loading the wrong version of process or breaking .nextTick.

I found two fixes :
- explicitly require process
- monkeypatch "process.nextTick = setImmediate" on line 513.

The first is cleaner (https://github.com/shukriadams/winston-daily-rotate-file/blob/ad8f2f798f3e71764edefb0206c3f9e3f0b5322e/index.js#L13)
I can submit a PR for it, but 1.7.2 doesn't live on its own branch, so I have nowhere to target the PR. Any suggestions?

**Comment by mattberther** [comment]
Can you make a branch based on the release commit at https://github.com/winstonjs/winston-daily-rotate-file/commit/525a941bf4aac26dc62406874b6d5bf7ecc85829?

**Comment by shukriadams** [comment]
Sure. But before I do that, is there a good reason for not explicitly importing process? Is it even normal? I just got a "process.umask is not a function" via a sub-package in the latest version of fs-extra, and I'm starting to wonder if it's my own npm setup that's breaking expected behavior. I'm on npm 6.9.0, node 10.16.3.
