### ISSUE TITLE
Log file contains only lots of "undefined"

### ISSUE THREAD

**Issue by FabianTe** [winstonjs/winston-daily-rotate-file#249]
Hi, when using the transport like this: 

```js
        return new ((winston.transports as any).DailyRotateFile)({
            filename: 'service-%DATE%.log',
            datePattern: 'DD-MM-YYYY',
            dirname: logFolder,
            zippedArchive: false,
            maxSize: '10m',
            maxFiles: '14d'
        });
```

and a custom winston format:

```js
winston.format.printf(({ level, message, label, timestamp }) => `${timestamp} ${level} [${label}]: ${message}`)
```

the output log file only contains lots of "undefined"

**Comment by mattberther** [comment]
`printf` takes an info object. Perhaps you're looking for:

``` javascript
winston.format.printf(info => `${info.timestamp} ${info.level} [${info.label}]: ${info.message}`)
```

**Comment by FabianTe** [comment]
I don't think that is my issue. In fact, my callback function uses a deconstructor to receive those properties.

This printf usage does work. I use a console transport along with the transport of this package and my console output is as expected.

**Comment by FabianTe** [comment]
Sorry, I completely removed my format and used the default one and then it works.
