### ISSUE TITLE
Log rotation on Electron not respecting maxFiles configuration

### ISSUE THREAD

**Issue by ramaralo** [winstonjs/winston-daily-rotate-file#251]
I'm trying to implement log rotation on Electron.
(*Due to other app requirements, I'm also trying to have different loggers so that different modules can have a custom log entry with the corresponding module name, so the loggers are obtained with a log factory. Sorry for the long code.*).
The implementation is as follows:

```javascript
const util = require('util');
const path = require('path');
const { DateTime } = require('luxon');
const winston = require('winston');
const { format, transports } = require('winston');
require('winston-daily-rotate-file');
const symlinkDir = require('symlink-dir');

const { combine, label, printf, timestamp } = format;

const utils = require('./utils/utils');
const { LOGS } = require('../config/config');

let log;
const LOGS_FILE_FULL_PATH = path.join(utils.getLogLocation(), `${LOGS.FILE.NAME}.${LOGS.FILE.EXTENSION}`);

const buildLogEntry = (data) => {
    const dateTime = DateTime.fromISO(data.timestamp).toFormat('yyyy-MM-dd HH:mm:ss');
    const level = data.level;
    const label = data.label;
    const message = `${data.message} ${util.format(...data[Symbol.for('splat')] || [])}`;

    return `[${dateTime}] [${level}] [${label}] - ${message}`;
};

const getTransports = (areFileLogsDisabled) => {
    if (areFileLogsDisabled) {
        return [ new transports.Console() ];
    }

    const transport = new (transports.DailyRotateFile)({
        filename: '/Library/Logs/MyApp',
        datePattern: 'YYYY-MM-DD-HH-mm-ss',
        zippedArchive: false,
        maxSize: '5mb,
        maxFiles: 3,
        utc: false,
        auditFile: '/Library/Application Support/MyApp'
    });

    return [transport];
};

const buildLoggerApi = (areFileLogsDisabled) => {
    return {
        getLogger: (module = 'default') => {
            if (!winston.loggers.has(module)) {
                winston.loggers.add(module, {
                    format: combine(
                        winston.format.colorize(),
                        label({ label: module }),
                        timestamp(),
                        printf((data) => buildLogEntry(data))
                    ),
                    transports: getTransports(areFileLogsDisabled)
                });
            }

            return winston.loggers.get(module);
        }
    };
};

const init = (areFileLogsDisabled = false) => {
    const loggerApi = buildLoggerApi(areFileLogsDisabled);

    // removed some other code not relevant for this example

    return loggerApi;
};

module.exports = {
    init
};
```

So this factory is used like this:
```javascript
// on Electron index.js file
const initializedLoggerFactory = loggerFactory.init(process.env.DISABLE_LOGS);
```

Then `initializedLoggerFactory` is passed as argument to other modules where they call:
```javascript
// on moduleA
const log = initializedLoggerFactory.getLogger('moduleA');
log.info('some info');

// on moduleB
const log = initializedLoggerFactory.getLogger('moduleB');
log.info('some info');
```
**Observed behaviour**
- When app starts two files are always created:
`
-rw-r--r--  1 user  DOM\Domain Users  2099 Nov  4 10:56 MyApp-2019-11-04-10-56-47.log
-rw-r--r--  1 user  DOM\Domain Users   211 Nov  4 10:56 MyApp-2019-11-04-10-56-49.log
`
- When I minimize and restore the app, each time the app is restored, another log file is created but end up with more files than those configured at `maxFiles`. For example:
```
211 Nov  4 10:56 MyApp-2019-11-04-10-56-49.log
181 Nov  4 10:59 MyApp-2019-11-04-10-59-28.log
181 Nov  4 10:59 MyApp-2019-11-04-10-59-46.log
181 Nov  4 11:01 MyApp-2019-11-04-11-01-19.log
```
And the audit file has:
```
{
    "keep": {
        "days": false,
        "amount": 3
    },
    "auditLog": "/....../Library/Application Support/fuze-join/logAudit.json",
    "files": [
        {
            "date": 1572865168600,
            "name": "/..../Library/Logs/MyApp/MyApp-2019-11-04-10-59-28.log",
            "hash": "d5fcfc2fce1fdf14bf3da0373ad8de68"
        },
        {
            "date": 1572865186174,
            "name": "/...../Library/Logs/MyApp/MyApp-2019-11-04-10-59-46.log",
            "hash": "a3c1a9018bd894a8c5725ced22ad4e2b"
        },
        {
            "date": 1572865279109,
            "name": "/......../Library/Logs/MyApp/MyApp-2019-11-04-11-01-19.log",
            "hash": "651d2565fdbe3f321772786f3ebfddec"
        }
    ]
}
```

**Expected behaviour**
- No more than 3 files should exist

**Question**
Is this expectation correct? I mean, the files don't reach maxSize they are just created because the app is restarting over and over again. In this case, should the logger delete files that are not on the audit list?

**Comment by mattberther** [comment]
Not sure if this is intended, but your `datePattern: 'YYYY-MM-DD-HH-mm-ss'` will create a new log file every second. Perhaps you want an hourly or daily log rotation instead. If so, you can remove the`mm-ss` from the `datePattern`.

Regarding your questions:

> Is this expectation correct?

Yes. However, the purge only happens upon log rotation.

> In this case, should the logger delete files that are not on the audit list?

No. The logger will not delete any files it does not know it created.

Please re-open if the issue persists after adjusting your date pattern.

**Comment by ramaralo** [comment]
Thanks!
I can probably have the datePattern set to `YYYY-MM-DD`. But if I test it with (notice the maxSize):
```javascript
const transport = new (transports.DailyRotateFile)({
        filename: '/Library/Logs/MyApp',
        datePattern: 'YYYY-MM-DD-HH-mm-ss',
        zippedArchive: false,
        maxSize: '3000',
        maxFiles: 3,
        utc: false,
        auditFile: '/Library/Application Support/MyApp'
    });
```

Rotation is not happening: 
`-rw-r--r--  1 user  DOMAIN\Domain Users  4808 Nov  5 10:44 MyApp-2019-11-05.log`

**Comment by ramaralo** [comment]
Yes meanwhile I tested with an integer and it rotated the files. However still two questions:

- Is it normal to have files over the maxSize (notice the .2 file)?
```
5765 Nov  5 15:02 MyApp-2019-11-05.log.2
3180 Nov  5 14:58 MyApp-2019-11-05.log.3
1630 Nov  5 15:02 MyApp-2019-11-05.log.4
```

- I notice that once rotation starts, files are appended with an incremental `.n`. Is this behaviour customisable? For example, have logs written to `MyApp-2019-11-05.log` and then on rotation, create files like: `MyApp-2019-11-05-15:13:32.log`. Can the rotation event be used for this?

Thanks!

**Comment by mattberther** [comment]
> Is it normal to have files over the maxSize (notice the .2 file)?

This can be possible if you stop and start the application, but should typically clean up after subsequent rotations (assuming you dont change the options hash that would result in creating a new audit file).

> I notice that once rotation starts, files are appended with an incremental .n. Is this behaviour customisable?

Yes, use the `filename` and `extension` properties. For example:

``` javascript
    const transport = new (transports.DailyRotateFile)({
        filename: '/Library/Logs/MyApp-%DATE%',
        extension: '.log',
        datePattern: 'YYYY-MM-DD-HH,
        ...
    });
```

**Comment by vkolova** [comment]
I am experiencing the same thing and in my opinion, this behavior is a bug. I want my log files to have `YYYY-MM-DD-HH-mm-ss` time format in them, but I don't want it to create new files every second. I just want to have the log start timestamp in the file name. Is there a way to go around this?

**Comment by mattberther** [comment]
This is not currently possible. As this is a rotating logger, it will name the files based on the rotation pattern.

**Comment by ramaralo** [comment]
Hi, I see some activity on this just to say I ended up using Electron-log.
Thanks.
