### ISSUE TITLE
How to log plain text instead of JSON

### ISSUE THREAD

**Issue by FabianTe** [winstonjs/winston-daily-rotate-file#253]
Hi, is there a way to not log JSON but instead a custom format?

**Comment by mattberther** [comment]
You could look at implementing a custom formatter. Examples and instructions are at https://github.com/winstonjs/winston#formats.

**Comment by FabianTe** [comment]
That's again not really what I ment.

I know about using formatters (and custom ones too) on the logger level.

But I need to use a specific logger only on the transport for winston-daily-rotate-file.

Does this package suppor that?

**Comment by mattberther** [comment]
You can add a custom formatter to the transport using the `format` property.

``` javascript
const myFormat = winston.format.printf(({ level, message, label, timestamp }) => {
      return `${timestamp} [${label}] ${level}: ${message}`;
});

const fileTransport = new DailyRotateFile({
    ...
    format: winston.format.combine(
        winston.format.label({label: 'right meow!' }),
        winston.format.timestamp(),
        myFormat
    )
});

winston.configure({
    transports: [
        fileTransport,
        new winston.transports.Console({})
    ]
});
```

The above code implements a different format on the events sent to `winston-daily-rotate-file`.

**Comment by FabianTe** [comment]
Thank you! Guess I didn't see it in the documentation.
