### ISSUE TITLE
query Interface (logger.query(options,callback)) not available on Version 4.2.1

### ISSUE THREAD

**Issue by Bussinho** [winstonjs/winston-daily-rotate-file#255]
Hello Guys,

for our project we need the function:
query(options?: QueryOptions, callback?: (err: Error, results: any) => void): any;

In the version 4.2.1 there is no function like this, so we get en undefined error.

Is there an other way to handle the query interface?

We have therefore version 3.8.0 installed.

**Comment by mattberther** [comment]
`winston-daily-rotate-file@4` removed support for `winston@2` and the transport interfaces provided by it. As a result, the `query` method was removed. You can review the implementation starting at https://github.com/winstonjs/winston-daily-rotate-file/commit/c1d1a3a6b19228f66d9d02872d23943cc8f8ceba#diff-5d4b74ff1561d45e3881ca3ae6a11f77L162 and could consider incorporating a variation of it into your project.

**Comment by dplewis** [comment]
> the transport interfaces provided by it. As a result, the query method was removed.

Query doesn't look like it rely on winston (maybe normalizeQuery but that just sets default options).

Is it possible to add it back?
