### ISSUE TITLE
maxFiles not work as expected after the server restart

### ISSUE THREAD

**Issue by wdetac0822** [winstonjs/winston-daily-rotate-file#264]
I use `winston` and `winston-daily-rotate-file` for server logging. I have set the transports as follow:

```
new winston.transports.DailyRotateFile({
  filename: 'logs/server-%DATE%.log',
  datePattern: 'YYYY-MM-DD HH:mm:ss',
  maxFiles: 10
})
```

I expect 1 log file every second and a maximum of 10 log files. It works as expected until the server restart. When the server restart, the counter restart, another 10 log files are generated. My expectation is the counter should not reset after the process restart.

My real situation is set `maxFiles` to `30d`. I consistently update the code for new features, I have to restart the server every week. As a result, no single log files are removed.

**Comment by mattberther** [comment]
@wdetac0822 I'm unable to reproduce the issue. Please review the gist I made of my test script and the output of `ls -al logs` after runs of the test script. If you have a way to reproduce this issue, please provide the script and reopen this issue so I can investigate further.

https://gist.github.com/mattberther/bfe795cc9915e707991725825ee1e2dd
