### ISSUE TITLE
Please update file-stream-rotator dep to 0.5.6 and publish new version

### ISSUE THREAD

**Issue by Apollon77** [winstonjs/winston-daily-rotate-file#265]
We found a bug in file-stream-rotator (https://github.com/rogerc/file-stream-rotator/issues/65) and now we have a published 0.5.6 with a fix. because it breaks out application I would like to ensure that users get the fixed sub-dep when updating. So (at least as I know) to get that we also need a new version from inston-daily-rotate-file with the new dep as minimum version in order to ensure this.

Could you please update dep and catch up? 

I could also do a PR if it helps... thank you @mattberther

**Comment by mattberther** [comment]
I'd like to see https://github.com/rogerc/file-stream-rotator/pull/67 merged first to make sure calls to `console.*` are appropriately guarded before merging. @rogerc is good on reviewing PRs, so I expect this won't be too long. Thanks!

**Comment by Apollon77** [comment]
I thank you. This makes a lot of sense.

**Comment by Apollon77** [comment]
@mattberther @rogerc published new version 0.5.7 ... you could go ahead :-) Thank you!

**Comment by Apollon77** [comment]
@mattberther Did you found time to look into the new version from Roger and my other PR topic?

**Comment by Apollon77** [comment]
@mattberther Sorry for pushing here that hard, but any chance for a fast release? 3k+ users are affected by these two bugs with a high chance of crashes around midnight each day ... I'm blocked to relese a fix by the missing update...
Can I support somehow? Should I rewoork something on my PR for the other fix? I support the best I can

**Comment by mattberther** [comment]
Resolved and pushed as `winston-daily-rotate-file@4.4.2`.

**Comment by Apollon77** [comment]
Thank you very much!!
