### ISSUE TITLE
Different filename for most recent log without using symlinks

### ISSUE THREAD

**Issue by deekshachaudhary** [winstonjs/winston-daily-rotate-file#267]
I'm trying to remove the date string from the most recent log name (service.log instead of service.log.2020-01-23) but having the date in all other logs. Is there a way to do this without using a symlink? The software consuming the logs has issues with symlinks.

**Comment by mattberther** [comment]
Unfortunately not at this time. What particular problem are you having with the symlink functionality?

**Comment by deekshachaudhary** [comment]
The logs were going to get consumed by another team who has had problems with symlink in the past, I don't have all the details but I'm fine to close this for now since the functionality is there, it was more of a question.
