### ISSUE TITLE
Latest log file name not to have number extension

### ISSUE THREAD

**Issue by saurabhchourasia9** [winstonjs/winston-daily-rotate-file#268]
By default latest log file name is logfilename.log.(max number). Is it possible to use it other way round so that latest log file name is logfilename.log and oldest is logfilename.log.(max number)?

**Comment by mattberther** [comment]
This is not currently possible. I’d welcome a PR with this capability.

**Comment by saurabhchourasia9** [comment]
createSymLink feature solved my issue. As it always points to latest file I can always refer to that name to view the latest log.
