### ISSUE TITLE
Can we get a release with prepend option pushed to npm?

### ISSUE THREAD

**Issue by grug** [winstonjs/winston-daily-rotate-file#27]
I'd like to use the prepend functionality for my log names, however v1.0.1 and v1.0.0 both don't have this. Is there any chance we can get a release that has the prepend functionality supported.

Thanks!

**Comment by mattberther** [comment]
@grug: im just transitioning into the maintainer role and unfortunately @indexzero is out of pocket as he's moving cross-country. 

At this point, I dont have the capability to push a new release to npm, but need to coordinate this permission with @indexzero. That said, if you need the release now, you can always add the `package.json` dependency to refer to the github project:

```json
{
  "dependencies": {
    "winston-daily-rotate-file": "winstonjs/winston-daily-rotate-file"
  }
}
```

Sorry for the inconvenience and thanks for your patience through the transition.

**Comment by grug** [comment]
@mattberther Thank you so much for the prompt response!

That's all good - happy to wait til until an npm release!
