### ISSUE TITLE
When log file created, I could see some .820ca04ef7dab2efbd963ed1f36c548395ce742c-audit.json file created, what is this? 

### ISSUE THREAD

**Issue by alexsunwei** [winstonjs/winston-daily-rotate-file#277]
When log file created, I could see some .820ca04ef7dab2efbd963ed1f36c548395ce742c-audit.json file created, what is this? 

Is there a way that we could avoid create this file?

**Comment by mattberther** [comment]
This is the name of the audit file that keeps track of the log file names so that it can rotate out properly. It's needed for this transport to function, but you can rename it using the `auditFile` option.
