### ISSUE TITLE
no such file or directory, open 'xxx\logs\application-info-2020-06-10 01:06:36.log'

### ISSUE THREAD

**Issue by MarxZhou** [winstonjs/winston-daily-rotate-file#278]
I am currently learning to use the current package.

I want to implement a function: generate a new log file every 10 seconds, the maximum number of log files is 6. Every new minute will replace the old file with a new log file.

I only succeeded when I ran the program for the first time, and the exception was thrown afterwards.

![image](https://user-images.githubusercontent.com/39861054/84183140-ff7acc00-aabd-11ea-9841-a8c30c6c9073.png)

I tried many times, but found that the program will always find some files that do not exist.

My operating system is windows, directly use nodemon and ts-node to run the written ts file.

Below is my code:
import winston from 'winston';
import 'winston-daily-rotate-file';

const infoTransport = new winston.transports.DailyRotateFile({
  filename: 'application-info-%DATE%.log',
  frequency: '10s',
  dirname: '../logs',
  datePattern: 'YYYY-MM-DD HH:MM:ss',
  zippedArchive: true,
  maxSize: '20m',
  maxFiles: 6,
  level: 'info',
});

infoTransport.on('rotate', (oldFilename: string, newFilename: string) => {
  // do something fun
  logger.info('create new info log file', { level: `info`, oldFilename, newFilename });
});

const errorTransport = new winston.transports.DailyRotateFile({
  filename: 'application-error-%DATE%.log',
  frequency: '10s',
  dirname: '../logs',
  datePattern: 'YYYY-MM-DD HH:MM:ss',
  zippedArchive: true,
  maxSize: '20m',
  maxFiles: 6,
  level: 'error',
});

errorTransport.on('rotate', (oldFilename: string, newFilename: string) => {
  // do something fun
  logger.info('create new error log file', { level: `error`, oldFilename, newFilename });
});

const logger = winston.createLogger({
  level: 'info',
  format: winston.format.json(),
  defaultMeta: { service: 'client' },
  transports: [
    // - Write all logs with level `info` and below to `application-info-%DATE%.log`
    infoTransport,

    // - Write all logs with level `error` and below to `application-error-%DATE%.log`
    errorTransport,
  ],
});

//
// If we're not in production then log to the `console` with the format:
// `${info.level}: ${info.message} JSON.stringify({ ...rest }) `
//
if (process.env.NODE_ENV !== 'production') {
  logger.add(
    new winston.transports.Console({
      format: winston.format.combine(winston.format.colorize(), winston.format.simple()),
    })
  );
}

let i = 0;
console.log(`i:`, i);
setInterval((): void => {
  i += 1;

  console.log(`logger:`, logger);

  logger.info(`This is an info log item ${i}`, {
    service: 'test',
  });

  logger.error(`This is an error log item ${i}`, {
    service: 'test',
  });
}, 1000);

export default logger;

**Comment by MarxZhou** [comment]
I just started the logging program in windows successfully.

**Comment by mattberther** [comment]
Thanks for the follow up, @MarxZhou. If there are areas that you believe are unclear in the documentation, I'd welcome a pull request to provide additional clarity.
