### ISSUE TITLE
Update version of winston

### ISSUE THREAD

**Issue by SimenB** [winstonjs/winston-daily-rotate-file#29]
We upgraded winston, and noticed we now bring in 2 of it.  

![image](https://cloud.githubusercontent.com/assets/1404810/14144880/e424c288-f691-11e5-8386-bf2af28ffd6a.png)

**Comment by mattberther** [comment]
Thanks for the report. I'll take a look at this.

**Comment by SimenB** [comment]
Maybe winston should be a peer dep for this project? Although many people hate peer-deps.

**Comment by mattberther** [comment]
@SimenB Ive been looking at this and this seems to be exactly the type of problem that peer dependencies are intended to solve. Specifically:

`winston-daily-rotate-file` is a library to be used by other projects, and this library uses `winston` and we would expect the user to work with both `winston` and `winston-daily-rotate-file` together.

Unless @indexzero objects, Im inclined to resolve this with a peer dependency.

**Comment by kidplug** [comment]
Is this module (daiy rotate file) going to bump the winston dependency to 2.2.0 ?

**Comment by mattberther** [comment]
@kidplug the PR (#31) is still open. Im waiting to merge them until I get permission from @indexzero to upload the new version to npm.

**Comment by mattberther** [comment]
@SimenB @kidplug Just pushed 1.1.0 to npm. winston should now be a peer dependency. Thanks for your patience.
