### ISSUE TITLE
NPM advisory - related to mkdirp 0.5.1 - please upgrade to ^0.5.5 - 

### ISSUE THREAD

**Issue by kidplug** [winstonjs/winston-daily-rotate-file#292]
Related to advisory:

https://www.npmjs.com/advisories/1179

```
-- winston-daily-rotate-file@1.7.2
  -- mkdirp@0.5.1
    -- minimist@0.0.8

```

Can you upgrade to mkdirp 0.5.5 ? (from 0.5.1) 

Thanks.

**Comment by mattberther** [comment]
`winston-daily-rotate-file@1.7.2` is 3 years old and is not actively patched. Recommend you update to a more recent version of the transport, which were already patched at https://github.com/winstonjs/winston-daily-rotate-file/commit/ab5dea2b8625c3d2e3be1286e7a548aea6a0b809.

**Comment by kidplug** [comment]
Seems like there are lots of breaking changes and options no longer available.
