### ISSUE TITLE
Can I submit a PR to replace moment with a more lightweight alternative?

### ISSUE THREAD

**Issue by sumeet-bansal** [winstonjs/winston-daily-rotate-file#294]
Hi @mattberther,

I'm trying to clean up some of my dependencies for a project and noticed this repo uses moment. Can I submit a PR to replace that dependency with a more lightweight alternative like [dayjs](https://github.com/iamkun/dayjs)? I just replaced moment with dayjs in my own project and liked it because it's much smaller but has a similar API, although I'm sure there're plenty of other similar libraries that could be used.

Thanks!

**Comment by sumeet-bansal** [comment]
Closing because it's a dependency of this, oops.

**Comment by ejohnso49** [comment]
@sumeet-bansal just a comment, but `winston` itself uses https://github.com/taylorhakes/fecha for its datetime package. It seems nice if this transport also used the same. But seeing as you found that the depenency, `file-stream-rotator`, uses `moment` as well, this does not seem simple.

**Comment by sumeet-bansal** [comment]
@ejohnso49 fecha seems like a better alternative in that case.
