### ISSUE TITLE
Feature request.(Rotate the logs when app is restarted)

### ISSUE THREAD

**Issue by edwinclement08** [winstonjs/winston-daily-rotate-file#299]
I think a good feature to have is to rotate the logs when the app is restarted.
This can be behind a flag defaulting to false.

This is helpful as it would allow easy debugging of issues that lead to a crash of the server. Right now, need to hunt throw the alert infrastructure to detect failure points, and then find the same point in the logs.

With this option, tailing the previous log will be enough.

**Comment by mattberther** [comment]
This transport has options to support tailing the log. You're probably looking for one or both of the following options:

    createSymlink: Create a tailable symlink to the current active log file. (default: false)
    symlinkName: The name of the tailable symlink. (default: 'current.log')

Please reopen with additional detail if this is not what you had in mind.
