### ISSUE TITLE
Tracking older DailyRotateFile issues from winston repository

### ISSUE THREAD

**Issue by indexzero** [winstonjs/winston-daily-rotate-file#3]
Now that `DailyRotateFile` is its own GitHub repository we need to track older issues created on the `winston` repository. 
 
- https://github.com/winstonjs/winston/issues/468
- https://github.com/winstonjs/winston/issues/456
- https://github.com/winstonjs/winston/issues/504
- https://github.com/winstonjs/winston/issues/691
- https://github.com/winstonjs/winston/issues/682

**Comment by mattberther** [comment]
@indexzero I've created issues in this repository for each of the items above. I've included a link to the original issue and tagged the reporter in each of the new issues.

I think we can close this one out.

**Comment by indexzero** [comment]
Thanks @mattberther. That feels like a better way to manage these issues.
