### ISSUE TITLE
NPM-package differs from master branch

### ISSUE THREAD

**Issue by LK1103** [winstonjs/winston-daily-rotate-file#30]
I installed winston-daily-rotate-file from NPM-registry. I tried to use the 'prepend' option but it did not work. The NPM-package differs from master branch since the NPM-package version does not contain the 'prepend' option while the github-version contains this option (I looked into both source codes).

**Comment by mattberther** [comment]
Thanks for the report. This has been captured in #27. Im waiting for @indexzero to return from holiday so that I can be granted permissions to push releases to npm.

Until then, you can refer to the github version in package.json:

```
{
  "dependencies": {
    "winston-daily-rotate-file": "winstonjs/winston-daily-rotate-file"
  }
}
```

Sorry for the delay.

**Comment by mattberther** [comment]
@phajduk @LK1103 Just pushed 1.1.0 to npm. This should be addressed now. Thanks for your patience.
