### ISSUE TITLE
Received unknown write error

### ISSUE THREAD

**Issue by Zaseth** [winstonjs/winston-daily-rotate-file#301]
We received the following error on our test service, causing it to crash. We don't know what caused it either. All I can say is that it's on a portable hdd.

```
node:events:356
      throw er; // Unhandled 'error' event
      ^

Error: UNKNOWN: unknown error, write
Emitted 'error' event at:
    at WriteStream.<anonymous> (E:\Projects\Node\Stew2\node_modules\file-stream-rotator\FileStreamRotator.js:677:15
```

**Comment by mattberther** [comment]
@Zaseth Additional information might be valuable here. Can you please post your configuration object, relevant node/winston/winston-daily-rotate-file verions, and a complete stack trace?

**Comment by Zaseth** [comment]
@mattberther I sadly don't have a stack trace... We're using v4.5.0 and for logging things we do the following:

```js
const textFormat = printf(({ level, message, timestamp }) => {
  return `[\x1b[36m${timestamp}\x1b[0m] [${level}] \x1b[35m>\x1b[0m ${message}`
})

const { debug } = createLogger({
  levels: { debug: 7 },
  transports: [
    new transports.DailyRotateFile({
      level: 'debug',
      maxFiles: '1d',
      filename: `./logs/${process.argv[2]}/debug@%DATE%.log`,
      datePattern: 'D-M-YYYY',
      format: combine(timestamp({ format: 'HH:mm:ss' }), json())
    }),
    new transports.Console({
      level: 'debug',
      format: combine(colorize(), timestamp({ format: 'HH:mm:ss' }), textFormat)
    })
  ]
})
```

**Comment by Zaseth** [comment]
Any news on this?

**Comment by mattberther** [comment]
I have been unable to reproduce this error. If you have a way to reliably reproduce this issue, please provide the smallest possible program that demonstrates this issue. Thank you.

**Comment by Zaseth** [comment]
@mattberther I don't have anything to provide other than the following:
- This issue has only happened on a portable HDD
- I already gave a snippet above

I know things would've been better with a stack trace, but none was given and this is all I know. I'm guessing it has something to do with the portable HDD being frozen, disallowing the daily rotate file not to be written. Feel free to close the issue if you want, it hasn't happened ever on our servers so that's a good sign I guess.

**Comment by mattberther** [comment]
Thank you. I'll close out, but please re-open if you have a way to consistently reproduce this problem.
