### ISSUE TITLE
Custom colors change does not work

### ISSUE THREAD

**Issue by pfcgarcia** [winstonjs/winston-daily-rotate-file#32]
It might be not an issue at all but currently it seems like I have to setup custom colors for every winston module installed in third-party transports.

For example if I use rotate file logger I need to get winston module used by winston-daily-rotate-file and amend it:

```
var winston = require("winston");
winston.addColors({ debug: "white" });

var winstonR = require("./node_modules/winston-daily-rotate-file/node_modules/winston/lib/winston")
winstonR.addColors({ debug: "white" });

```

Is there any way to overcome this?

**Comment by mattberther** [comment]
@pfcgarcia PR #31 should end up addressing this. Requiring winston as a peer dependency. Want to try pulling that branch and checking it out?

**Comment by pfcgarcia** [comment]
It's working, thanks.
