### ISSUE TITLE
FIPS Enabled Environment for Log Rotation

### ISSUE THREAD

**Issue by ZarifS** [winstonjs/winston-daily-rotate-file#322]
- It seems currently the log rotator uses the File Stream Rotator dependency which continues to use the MD5 method for hash generation.
- Changing this dependency and using a rotator that using SHA256 for example would allow the Winston Log Rotator component to satisfy crypto FIPS requirements.
- Is there any plans to include this feature into the package or open to PRs for it?

**Comment by mattberther** [comment]
@ZarifS I've been considering (for a variety of reasons) changing the dependency to use https://github.com/iccicci/rotating-file-stream instead. Can you confirm that this component provides the FIPS compliance you are seeking?

**Comment by mattberther** [comment]
Resolved with `winston-daily-rotate-file@4.7.1`.
