### ISSUE TITLE
want to create empty files even there is no logs

### ISSUE THREAD

**Issue by Celia-SSS** [winstonjs/winston-daily-rotate-file#325]
eg：
set datePattern: 'YYYY-MM-DD-HH'
between 2021-08-05-10 and 2021-08-05-11,  no logs genareted
but i want  winston-daily-rotate-file can created a log file for that period of time (maybe named as error.log.2021-08-05-10)

what should i do ?

**Comment by SuperKirik** [comment]
Hello @Celia-SSS ! 
Did you find the solution ?
