### ISSUE TITLE
Why Nodejs Requirement was increased in a minor update?

### ISSUE THREAD

**Issue by Apollon77** [winstonjs/winston-daily-rotate-file#334]
I just noticed that a minor update to 4.6.0 in late december (https://github.com/winstonjs/winston-daily-rotate-file/commit/76d1d11963f014fdff5913191c0c35b14fc127e5) just increased the required nodejs version. But I can not see any other dependenc that requires that really?

Yes Nodejs 10 ( and formally also 8) is EOL but doing that breaking change in an minor update breaks other applications. We use the library in ioBroker and the "current stable" version used to also support Nodejs 10, but now this is broken :-(

Can you please adjust that back and release a 5.0 with the breaking change? Or was there any reason?

Thank you for further information

**Comment by wbt** [comment]
Tagging @mattberther as the responsible party

**Comment by Apollon77** [comment]
I thought something like this ... maybe branch off from the "last version", do the release on the branch (or directly using npm publish in this case) and then directly publish a 5.0 from master? SOmething like that?

It is always the issue with devDeps (same for testing frameworks) not supporting the version ranges that the "prodiction deps" would allow  :-(

**Comment by mattberther** [comment]
`winston-daily-rotate-file@4.6.1` was just published which reverses the node engine requirement. Please let me know of any ongoing issues with this version.

**Comment by Apollon77** [comment]
Thank you very much @mattberther
