### ISSUE TITLE
Update readme add "level" option

### ISSUE THREAD

**Issue by Henderxx** [winstonjs/winston-daily-rotate-file#353]
Hi everyone, i was going through configuration of rotating files, and in one point i needed to specify few transports but each one for different levels, first i thought it was impossible with rotate file, but in other closed issues i found it as working (#262 ), and it works as expected, but it's not mentioned in readme

**Comment by wbt** [comment]
Thanks for pointing that out!  Would you be interested in making a PR containing text that would be helpful for someone in the situation you were in before figuring that out?

**Comment by Henderxx** [comment]
i'm not an expert in making PRs but i could try for sure

**Comment by wbt** [comment]
Thanks for the contribution!
