### ISSUE TITLE
Adding new Maintainers

### ISSUE THREAD

**Issue by Apollon77** [winstonjs/winston-daily-rotate-file#388]
Hi @mattberther,

as introduced in https://github.com/winstonjs/winston-daily-rotate-file/pull/366#issuecomment-1928020030 we as ioBroker use WIndoston and also this libaryr here in our core and iossues here lead to potential crashes of the Application. So we have a huge interesting in participating here to make sure we can update and ix issues to make ioBroker more stable and reliable.

If you check my GitHub profile you will see that I own severy own repositories, but also am very active in several other Smart home and iot based node.js projects. I also joined several as maintainer because of comparable reasons.

I can offer to support in maintaining here, reviewing. PRs and ideally approving and merging them. Depending on release processes I could also manage and support with releases.
Ideally there is also a second active developer so that changes canbe reviewed.

Tell me what you think and how we could continue. If relevant I'm also in Discord, telegram or other chat like systems for a more direct connection and discussion.

Ingo

**Comment by foxriver76** [comment]
As @Apollon77 already mentioned in the open PR, I am also open for maintaining. I think it makes sense to have a second person for reviewing PRs and distributing loads.

**Comment by Apollon77** [comment]
@mattberther @foxriver76 is another core team developer from ioBroker maintaining some of the central ioBroker projects in Backend and Frontend.

**Comment by mattberther** [comment]
@Apollon77 First and foremost, thank you for agreeing to take this on. I've simply not had the bandwidth to give this library the attention it deserves, and Im sure it will thrive under your direction.

I have sent an invite to you with maintainer access to the repository. Please also let me know your npmjs username, so that you can be provided the permission to publish new packages.

**Comment by Apollon77** [comment]
Thank you very much, my npmjs username is apollon77 (too). Are you ok if I also invite @foxriver76 (or you do?), so that we are two guys here. If you like to maintain processes you had in the past or such just tell ad we will respect them, for sure

**Comment by DABH** [comment]
Greetings from the main winston project!  First I wanted to thank @mattberther for all of his work on this project over the years.  There have been times when this transport was much more actively maintained than winston itself 🙃  And I think it's fair to say that the popularity of this transport has helped maintain the popularity of winston over the years, too.  Thank you!

Could I (as the lead winston maintainer; maintaining for ~10 years) be added on npm for this repo as well, just so we have an extra layer of redundancy there?  I'm already an admin on the repo here on GitHub but it would be nice to have the ability to do a release on npm if necessary.

Thanks again -- and thanks @Apollon77 @foxriver76 for stepping up!

**Comment by mattberther** [comment]
@foxriver76 has been added as a maintainer on this project. @Apollon77 and @DABH I added both of you to the npmjs repository. Please note that you will need MFA active in order to publish.

**Comment by mattberther** [comment]
I think this is it, but I'll leave this ticket open for now, while you work through any other transition items. Feel free to close whenever your ready.

**Comment by Apollon77** [comment]
Thank you, npm received.

i will update the one PR to adjust all "such places" ... then I check dependency updates too and we release a new version

**Comment by Apollon77** [comment]
@mattberther Whats your opinion to github action for also releases? We then might need a NPM token added as a secret. We have some convenient processes already in iobroker that use https://github.com/AlCalzone/release-script as very convenient way to automate releases. WDYT? If you wantto see that in action in a repo tell and I show a link

**Comment by DABH** [comment]
For other projects in the Winston ecosystem I just use `np` to do releases, it’s easy enough, generates GH release automatically, etc.  I’m supportive of whatever release strategy is easy for you guys, though.

**Comment by Apollon77** [comment]
@DABH Thx! Release script works a bit different: ou have it only as devDep and it handles version increase and if you like changelog handling. it then creates a tag and pushs to GitHub. There an action gets triggered by the tag push, catches the relevant changelog infos and publish to npm and create the releease for this tag and the changelog entry ... but yes in the end comparable.

BTW: Release scroipt also has a lerna plugin for monorepos and also a license year check plugin ... just saw that LICENSE here just states 2015 ... will also update this to 2015-2024 :) (just to be formal correct)

**Comment by mattberther** [comment]
Perhaps @DABH, as a member of winston core, can add you (@Apollon77) to the @winstonjs/daily-rotate-file team, which would provide Admin access to this project. Doing so, would allow you to manage your own secrets.

**Comment by DABH** [comment]
Good call -- @Apollon77 you should have received an invite to join that team, so you'll have admin access on the project now.

**Comment by Apollon77** [comment]
Ok, 5.0.0 released, so I would close here
