### ISSUE TITLE
npm package?

### ISSUE THREAD

**Issue by tsofist** [winstonjs/winston-daily-rotate-file#4]
DailyRotateFile removed from winston core, but winston-daily-rotate-file not yet registered on npm.
Thanks!

**Comment by demohi** [comment]
+ 1

**Comment by GlennGeenen** [comment]
+1

**Comment by reyazucar** [comment]
+1

**Comment by ddorkin-issart** [comment]
+1

**Comment by XemsDoom** [comment]
+1

**Comment by indexzero** [comment]
This is fixed. **THIS PROJECT IS NOW LOOKING FOR A NEW MAINTAINER.** ... I will be continuing work on `winston` itself with gusto, but do not plan on spending cycles on this transport. If you are interested please let me know.

**Comment by GlennGeenen** [comment]
You forgot to publish it to npm?

**Comment by macneib** [comment]
What's the npm package name for this?

**Comment by indexzero** [comment]
```
npm i winston-daily-rotate-file --save
```

**Comment by macneib** [comment]
Awesome thanks!
