### ISSUE TITLE
Log files are rotated every minute even if datePattern specifies only daily rotation

### ISSUE THREAD

**Issue by kumar-b** [winstonjs/winston-daily-rotate-file#40]
Even if the pattern is '.yyyy-MM-dd', the log files are rotated based on minutes. The new stream (self._createStream()) are opened even when the log files are one minute older (this._minute < now.getUTCMinutes()). https://github.com/winstonjs/winston-daily-rotate-file/blob/master/index.js#L395 . Also attempt to open next appropriate file also called each one minute and self._created is set to 0 every minute. https://github.com/winstonjs/winston-daily-rotate-file/blob/master/index.js#L551

I think the new stream creation should happen based on given pattern.

**Comment by mattberther** [comment]
Resolved by a07b8203abf9d630318315ea5274b029aacfc50e.
