### ISSUE TITLE
log file name changed since version 1.1.2

### ISSUE THREAD

**Issue by IoannesPaulus** [winstonjs/winston-daily-rotate-file#44]
The name of the log files has changed since version 1.1.2.

var rollingFileLogger = new(WinstonDailyRotFile)({
  timestamp: timeStamp,
  filename: 'logs/development/log',
  datePattern: '-yyyy-MM-dd.log'
});

Before: log-2016-06-06.log
After: log.-2016-06-06.log

**Comment by mattberther** [comment]
Thank you for your report. There appears to be a regression introduced at d17c0d86674fe067fe595c36de8fbf55a92d8910. Im in process of addressing now.

**Comment by mattberther** [comment]
The issue should be resolved -- while still maintaining the desired functionality from #38. Pushed to npm as v1.1.4.

Please dont hesitate to let me know if you continue to see problems.

**Comment by IoannesPaulus** [comment]
thanks for the quick resolution! :)
