### ISSUE TITLE
With maxfiles and maxsize options, older timestamped log files are not removed

### ISSUE THREAD

**Issue by kumar-b** [winstonjs/winston-daily-rotate-file#46]
When maxfiles option is set, for current timestapmed logfiles, it removes the oldfiles. For ex: if maxfiles=2 and pattern=.dd then on third rollover it will have logfile.01.log and logfile.01.log.1, Here it is deleting logfile.01.log and creating logfile.01.log.2

But if based on time rotation happens, it creates new timestamped log files say logfile.02.log, then it has no history of what files are there from previous timestamp. And it's not removing them.
Here in code 
https://github.com/winstonjs/winston-daily-rotate-file/blob/master/index.js#L588
it removes only files having current timestamp in the name.

How should we proceed from here? Should we keep a list of all existing log files and remove one when creating new?

**Comment by markjbyrne81** [comment]
Hi @mattberther,

Apologies for the number of commits in the pull request but I am new to github.

We needed this functionality for a project the I am currently working on and after seeing a couple of issues raised around the subject I thought I would share.  Hope you don't mind.

**Comment by markjbyrne81** [comment]
I might not be following you correctly but I have just created a pull request that I believe may provide the functionality that you're looking for.

https://github.com/winstonjs/winston-daily-rotate-file/pull/50

**Comment by mattberther** [comment]
@kumar-b Can you please review the latest code and see if @markjbyrne81's PR (#50) fixes things?

**Comment by kumar-b** [comment]
The reported issue occurs when both maxfiles and maxsize are set. Hopefully that is a valid scenario. The PR has fixed one part when only maxfiles is set. Now we have to combine both.

I guess the issue title was misleading. I have changed it now.

**Comment by KulykOleg** [comment]
Faced with same problem. Will be awesome to implement combination of both. Thanks.

**Comment by rootical** [comment]
Having exactly same problem on this end. Would be great to see this working since it is kind of a valid scenario.

**Comment by cronon** [comment]
have anyone fixed this or found workaround?

**Comment by mattberther** [comment]
Is this still an issue with the new option introduced with #83?

**Comment by mattberther** [comment]
Some long-overdue refactoring of the transport has occured. A PR is available at #107. Also, a pre-release version has been published to npm. Please `npm install winston-daily-rotate-file@2.0.0-beta` and reopen this issue if the problem remains.
