### ISSUE TITLE
Active/current log file with no date postfix?

### ISSUE THREAD

**Issue by bitsofinfo** [winstonjs/winston-daily-rotate-file#47]
Hi,
I need an option so that the current log file being written to is just *.log (no date suffix) is this not possible?

**Comment by mattberther** [comment]
I believe you should be able to set date format to '.log'.

**Comment by mattberther** [comment]
@bitsofinfo to close the loop on this: the following code *should* get you what you're requesting:

``` javascript
var fileTransportOpts = {
  filename: './server',
  datePattern: '.log'
};

var logger = new (winston.Logger)({
  transports: [
    new (winston.transports.DailyRotateFile)(fileTransportOpts)
  ]
});

logger.log('info', 'test message');
```

The last line will create a file called `server.log` in the current folder. Please re-open if this doesn't meet your needs.

**Comment by bitsofinfo** [comment]
That results in: `overwatch-sample-1.log..log`

Setting to just `log` = `overwatch-sample-1.log.log`

Will this still properly do rotation with this setting?

**Comment by mattberther** [comment]
Please provide the code you're using. Im unable to reproduce. The sample I posted above creates appropriately named log files. Make sure that you're specifying `filename` properly. In your case, it looks like you want `filename: 'overwatch-sample'` and `datePattern: '.log'`.

**Comment by bitsofinfo** [comment]
Yeah when I did that the name is as expected, my other question is still the main question: 

Will this still properly do rotation with this setting?

**Comment by mattberther** [comment]
I would expect it to rotate, assuming you have maxsize set. Obviously, it wouldn't rotate on date. Please let me know if you see different behavior.

**Comment by bitsofinfo** [comment]
Ok, if it won't do the date based rotation, not much point in using it. I really think this should support the option of the current log file having no suffix and only older log files having the date.

**Comment by zoell** [comment]
Is it possible to add this feature so the current log file is alone without the date and it will rotate on date also?

So like:
current: the_log_file.log
yesterday: the_log_file.log..2017-02-07
etc?

**Comment by sumitjainn** [comment]
Please reopen the issue.. it would be really useful if it supports both: current file without date suffix and date based log rotation.

**Comment by mattberther** [comment]
@sumitjainn the transport supports date-based log rotation. For the other piece of your request, follow #23.

**Comment by shivang2joshi** [comment]
@sumitjainn you can add two separate transports. one logs into current.log, second with DailyRotateFile support. Add some memory limit for current.log

**Comment by galamo** [comment]
Hi 
is this issue solved? is there a configuration for winston to apply this behaviour ?

So like:
current: the_log_file.log
yesterday: the_log_file.log..2017-02-07
etc?

**Comment by mattberther** [comment]
Try the configuration at https://github.com/winstonjs/winston-daily-rotate-file/issues/310, @galamo.

**Comment by Rychu-Pawel** [comment]
`datePatern` has to be inside square brackets these days and without the dot so the correct workaround is now 
```
var fileTransportOpts = {
  filename: './server',
  datePattern: '[log]'
};
```
