### ISSUE TITLE
Custom level + Transports + Colorize

### ISSUE THREAD

**Issue by brunolemos** [winstonjs/winston-daily-rotate-file#48]
When I create a custom level using `setLevels` and `addColors` without adding DailyRotateFile, it works fine. But when using a Transport with `colorize: true`, I get the following error:

```
uncaughtException: Cannot read property 'match' of undefined
at /node_modules/winston-daily-rotate-file/node_modules/winston/lib/winston/config.js:30:28
```

I believe it's because the winston instance is different. The transport is not using the winston that has my custom level.

How to make that work? I believe DailyRotateFile should receive the winston instance as an option, like other transports does. (e.g: bithavoc/express-winston)

**Comment by mattberther** [comment]
@brunolemos thanks for your report. I tried recreating your problem with the following code but am unable to.

```
var myCustomLevels = {
  levels: {
    foo: 0,
    bar: 1,
    baz: 2,
    foobar: 3
  },
  colors: {
    foo: 'blue',
    bar: 'green',
    baz: 'yellow',
    foobar: 'red'
  }
};

var fileTransportOpts = {
  filename: './colorize.log',
  colorize: true
};

var logger = new (winston.Logger)({
  transports: [
    new (winston.transports.DailyRotateFile)(fileTransportOpts)
  ],
  levels: myCustomLevels.levels
});

logger.foobar('test message');
```

Let me know if your code does something different. 

Regarding the winston instance being different. The newest versions of `winston-daily-rotate-file` use winston as a peer dependency, so make sure you have the most recent version of winston installed with your software library.

**Comment by brunolemos** [comment]
Hi @mattberther, just noticed I was using my outdated fork. Updating to the newest version of `winston-daily-rotate-file` (which uses peer dependency) works fine. Thanks!
