### ISSUE TITLE
Find a new maintainer for this transport

### ISSUE THREAD

**Issue by indexzero** [winstonjs/winston-daily-rotate-file#5]
**THIS PROJECT IS NOW LOOKING FOR A NEW MAINTAINER.** I will be continuing work on `winston` itself with gusto, but do not plan on spending cycles on this transport. 

If you are interested please let me know.

**Comment by kbariotis** [comment]
hello @indexzero I'm interesting on maintaining this package. I am Kostas Bariotis, a Goodvid.io Software Engineer. Would you be interested to discuss it?

**Comment by lillem4n** [comment]
Hi, I'm interested in helping a bit. Having a look at pull requests and issues.

**Comment by indexzero** [comment]
@lillem4n great! And @kbariotis: sorry I missed the notification from you :(

... the first step here is doing triage on the open bugs and pull requests to see what the common pitfalls / problema are. 

If you're looking those over now @lillem4n I'd love to hear your thoughts.

**Comment by Carlos487** [comment]
I would also like to help. I'm Carlos Fabara a software developer with experience on .net, javascript and java.

**Comment by springuper** [comment]
count me in, I'm ShangChun as a frontend engineer of Meituan in china.

**Comment by mattberther** [comment]
Hi @indexzero -- excited to be considered to maintain this project going forward. What are the next steps?

**Comment by indexzero** [comment]
@mattberther you have been the first person to start the triage process so I've made you a maintainer.

@Carlos487 @springuper @lillem4n @kbariotis are you all still interested? If so please work with @mattberther on the issues he's triaged.

**Comment by mattberther** [comment]
Thanks @indexzero. Ill close this issue out.

**Comment by lillem4n** [comment]
Sorry, a lot of work came my way. Just working through the backlog now. I think I'm better as a occasional patcher and pull requester than a regular maintainer. :)
