### ISSUE TITLE
should create directory if it does not exist

### ISSUE THREAD

**Issue by h2oboi89** [winstonjs/winston-daily-rotate-file#54]
if you specify a directory in options (options.dirname) that does not exist yet then no files will be created and no errors will be emitted (fails silently).

``` js
'use strict';

const winston = require('winston');
const FileRotator = require('winston-daily-rotate-file');
const path = require('path');

var logger = new(winston.Logger)();

logger.level = 'silly';

logger.add(FileRotator, {
  datePattern: 'yyyy-MM-ddTHH:mm',
  dirname: path.join(__dirname, 'logs'),
  filename: 'output.log',
  json: false,
  formatter: (options) => `foo, bar, baz: ${options.level} ${options.message}`
    // prepend: true
});

let i = 0;
setInterval(() => {
  logger.info(`floof: ${i++}`);
}, 1000);
```

**Comment by mattberther** [comment]
I think you probably want to handle the error event from the logger:

```js
var mkdirp = require('mkdirp');
logger.on('error', function(err) {
  if (err.code == 'ENOENT') {
    mkdirp.sync(path.join(__dirname, 'logs'));
  }
});
```

**Comment by ken-kuro** [comment]
> I think you probably want to handle the error event from the logger:
> 
> ```js
> var mkdirp = require('mkdirp');
> logger.on('error', function(err) {
>   if (err.code == 'ENOENT') {
>     mkdirp.sync(path.join(__dirname, 'logs'));
>   }
> });
> ```

Sorry to bring this back. If you delete the directory, it will not be re-created until you restart the app, and the daily-rotate-file transport or logger won't throw any error either.
