### ISSUE TITLE
mangles file names

### ISSUE THREAD

**Issue by h2oboi89** [winstonjs/winston-daily-rotate-file#55]
If you specify a file extension in `options.filename` it comes before the timestamp if `options.prepend` is false.

ie: `{filename: 'output.log'}` => `output.log2016-09-08T18:58`

a better solution would be to accept an extension argument or use `path.extname` to get it from the file name

ie: `{filename: 'output.log'}` => `output2016-09-08T18:58.log`
or: `{filename: 'output', extension: 'log'}` => `output2016-09-08T18:58.log`

See #54 for sample code

**Comment by mattberther** [comment]
Thanks @h2oboi89 - this has bothered me to some extent as well. Ill consider how we might implement this -- while retaining backwards compatibility.

**Comment by dprosper** [comment]
doing with what you have you can modify the construct a little to get to your desired result.  

  var transport = new winston.transports.DailyRotateFile({
    filename: './output',
    datePattern: 'yyyy-MM-dd.log',
    prepend: false,
    level: process.env.ENV === 'development' ? 'debug' : 'info'
  });

so the extension is not in the filename, but in the datePattern.  Probably not what the author intended, but should work.

**Comment by mattberther** [comment]
Thanks @dprosper - this is what we're doing right now as well. It works. Id be happy to consider a PR if someone wants to put one together. Otherwise, I think Im going to close this out.
