### ISSUE TITLE
Cannot launch container in production mode.

### ISSUE THREAD

**Issue by mitesh-mokko** [winstonjs/winston-daily-rotate-file#56]
I have created an app using the following set of major modules:

yeoman generator-angular-fullstack (> 4.0.0)

and added in
"parse-server": "^2.2.18"

This parse server uses winston and winston-daily-rotate-file; and uses babel (es2015 preset).

During development everything goes fine but when I deploy over dokku (heroku-ish), I get the following error on the server (and the app fails to launch):

/app/node_modules/winston-daily-rotate-file/index.js:180
       winston.transports.DailyRotateFile = DailyRotateFile;
                                          ^
TypeError: Cannot set property DailyRotateFile of #<Object> which has only a getter
           at Object.<anonymous> (/app/node_modules/winston-daily-rotate-file/index.js:180:36)

Since dokku installs dependencies automatically, and I'm not an expert, I have no way of deploying the application with my currently known set of tools..

Any help?

**Comment by mattberther** [comment]
@mitesh-mokko sorry that you're having problems. Can you gist the output of `npm ls` from your project folder, and then also from the docker container?

**Comment by theProtagony** [comment]
I'm so sorry I'm very new to "gist". Any help there?

**Comment by theProtagony** [comment]
Never mind - it was so simple. I've just never used it.

**Comment by theProtagony** [comment]
[gist from project folder](https://gist.github.com/theProtagony/33d4c971f78a5ace6c778a9b5ec47b74)

Can't get a gist from docker container again until I re-create it.

**Comment by mattberther** [comment]
Thanks @theProtagony - let me know when you have one from the container and we can compare.

**Comment by xuefengwang** [comment]
I was getting the same error today. It's fixed for me by upgrading to winston 2.2.0 (my old version was 1.0.2). It seems it's related to winston was using __defineGetter__ method for transports in the old version. But in 2.2.0, that has been removed. Hope it helps.

**Comment by mattberther** [comment]
@xuefengwang thanks - I suspect its probably an out-dated Winston version. This becomes more apparent since we use Winston as a peer-dependency and not a direct reference.
