### ISSUE TITLE
order: 'desc' do not work with winston-daily-rotate-file

### ISSUE THREAD

**Issue by baseless** [winstonjs/winston-daily-rotate-file#59]
As described in title, it seems that descending order works fine as long as you use winston.transports.File. As soon as you switch to require('winston-daily-rotate-file') it acts as the old filetransport bug where sorting is done after the set number of rows has been retrieved in an ascending fascion.

**Comment by mattberther** [comment]
@baseless do you have a simple piece of code that demonstrates the problem? Thank you!

**Comment by baseless** [comment]
Sorry for the delay, been crazy busy. Will try to get you code sample asap.

**Comment by ipelovski** [comment]
Hi, I ran to the same behavior. The code that is responsible for this is in `DailyRotateFile.prototype.query` method, its `push(log)` inner function. What it does is that it stops collecting logs after the results size is greater than the desired rows. After the results array is full it is reversed. What may be a better behavior is to collect all logs, after that reverse it if necessary, and only than take the desired rows. Certainly there is a better way to do this, but this is the first that came to my mind.

**Comment by mattberther** [comment]
This should be fixed with npm 1.7.2. Please re-open if you find otherwise.
