### ISSUE TITLE
set custom formatter function, but not work!!!

### ISSUE THREAD

**Issue by liubin1777** [winstonjs/winston-daily-rotate-file#60]
const LOGGER_FILE_MAX_SIZE = 1024 * 1024 * 20;//20MB
const dateFormat = function() {
  return moment().format('YYYY-MM-DD HH:mm:ss.SSS');
};
const defaultLoggerTransport = new DailyRotateFile({
    name: 'defaultLog',
    filename: all.log,
    timestamp: dateFormat,
    level: 'info',
    colorize: true,
    maxsize: LOGGER_FILE_MAX_SIZE,
    datePattern: '.yyyy-MM-dd',
    formatter: function(options) {
    // Return string will be passed to logger.
    return options.timestamp() +' '+ options.level.toUpperCase() +' '+ (undefined !== options.message ? options.message : '') +
        (options.meta && Object.keys(options.meta).length ? '\n\t'+ JSON.stringify(options.meta) : '' );
  }
  });

**Comment by mattberther** [comment]
You will need to set json to false to use the custom formatter function:

```js
const LOGGER_FILE_MAX_SIZE = 1024 * 1024 * 20;//20MB

const dateFormat = function() {
    return moment().format('YYYY-MM-DD HH:mm:ss.SSS');
};

const defaultLoggerTransport = new DailyRotateFile({
    name: 'defaultLog',
    filename: 'all.log',
    timestamp: dateFormat,
    level: 'info',
    colorize: true,
    maxsize: LOGGER_FILE_MAX_SIZE,
    datePattern: '.yyyy-MM-dd',
    json: false,
    formatter: function(options) {
        // Return string will be passed to logger.
        return options.timestamp() +' '+ options.level.toUpperCase() +' '+ (undefined !==      options.message ? options.message : '') +
            (options.meta && Object.keys(options.meta).length ? '\n\t'+ JSON.stringify(options.meta) : '' );
    }
});
```
