### ISSUE TITLE
Logging Weekly

### ISSUE THREAD

**Issue by dhruv004** [winstonjs/winston-daily-rotate-file#65]
Can we log files weekly?If so is there any example

**Comment by mattberther** [comment]
This should be resolved with #66.

**Comment by dhruv004** [comment]
What I want to do is to repeat log files weekly not for weekday.So for example from Monday to next Monday. Should I just pass 

> datePattern: 'Mon',

Also I want to add the week pattern to the filename.This is what I was trying

`const tsFormat = () => (new Date()).toLocaleTimeString();`

`const logger = new (winston.Logger)({`       
  `      transports: [`
`    new (require('winston-daily-rotate-file'))({`
 `     filename: `${logDir}/-results.log`,`
`    timestamp: tsFormat`,
`      datePattern: 'ddd',`
`      prepend: true`
`    })`
` ]`
`});`
