### ISSUE TITLE
Default for `timestamp` has changed from true to false.

### ISSUE THREAD

**Issue by q42jaap** [winstonjs/winston-daily-rotate-file#67]
https://github.com/winstonjs/winston-daily-rotate-file/commit/aa28f522718778fe8210ced1090353ffc29c6f31

This breaks compatibility with File transport from winston:
https://github.com/winstonjs/winston/blob/master/lib/winston/transports/file.js#L84

Timestamp is supposed to be true by default.

Given that this changed in a point release, I assume this was a mistake.

**Comment by mattberther** [comment]
Thank you for the report. A mistake. Pushed as v1.4.3.
