### ISSUE TITLE
Timestamp option set to 'false' always overridden to 'true'

### ISSUE THREAD

**Issue by wickedcodeferret** [winstonjs/winston-daily-rotate-file#70]
In DailyRotateFile, a provided option.timestamp set to **false** will always be overridden to **true** by  the following logic:
```
this.timestamp = options.timestamp || true;
```
This assignment should be updated to allow an option.timestamp explicitly set to **false** to pass through to winston for users who do not wish to prepend log output with a timestamp.

**Comment by mattberther** [comment]
Thanks for the report. Resolved with https://github.com/winstonjs/winston-daily-rotate-file/commit/d0d804b18ad2dacc47682a57db5bdf87a8bbf878 and pushed to npm as 1.4.4.
