### ISSUE TITLE
datePattern folder do not exist

### ISSUE THREAD

**Issue by protzi** [winstonjs/winston-daily-rotate-file#72]
Hello, please help to find a way to solve this problem
i want to separate log files by day in the folder

```
2017-02-15
 - errors.log
 - warning.log
 - etc...
2017-02-16
 - errors.log
 - warning.log
 - etc...
```

My date pattern loook like this
`datePattern: '../yyyy-MM-dd/.log',
createTree: true
`

But i get an error.code ===  'ENOENT'

Where should i catch this error so  my log wasn't lost and folder created ?

**Comment by mattberther** [comment]
@protzi 1.7.0 was just pushed to npm which supports the createTree option. Please try that version and report back if there are continued problems.
