### ISSUE TITLE
Port performance fixes from winston file transport 

### ISSUE THREAD

**Issue by pwielgolaski** [winstonjs/winston-daily-rotate-file#76]
Especially stream2 

https://github.com/winstonjs/winston/commit/b0227b6c27cf651ffa8b8192ef79ab24296362e3
https://github.com/winstonjs/winston/commit/5c4bd4191468570e46805ed399cad63cfb1856cc

We see few minutes hangs in web application with heavy load when we use daily-rotate vs file transport

**Comment by mattberther** [comment]
Some long-overdue refactoring of the transport has occurred. A PR is available at #107. Also, a pre-release version has been published to npm. Part of the refactor involved moving the bulk of the logging and rotation to a separate library.

Please `npm install winston-daily-rotate-file@2.0.0-beta` and reopen this issue if the problem remains.
