### ISSUE TITLE
Rotate filename format

### ISSUE THREAD

**Issue by JujuChang** [winstonjs/winston-daily-rotate-file#79]
datePattern can and will only prepend at the beginning of the filename. Something like 'dev-2017-05-17-apps.log' can't be done. Please allow users to determine the filename format on where to place the date.

**Comment by sandman45** [comment]
Yea this would be awesome.  We want to do this `idt-2017-01-10.log` but i cannot as it is currently

**Comment by JujuChang** [comment]
I have overwritten some of the winston functions to achieve this.

**Comment by mattberther** [comment]
Some long-overdue refactoring of the transport has occured. A PR is available at #107. Also, a pre-release version has been published to npm. 

A key feature of the refactoring is that you can now put %DATE% anywhere in your filename. Also, momentjs formats are used so you have much more control over the final filename. Review the PR to see the updated options.

Please `npm install winston-daily-rotate-file@2.0.0-beta` and reopen this issue if the problem remains.
