### ISSUE TITLE
datePattern and text prefixes

### ISSUE THREAD

**Issue by steeply** [winstonjs/winston-daily-rotate-file#81]
If you use prefixes or any word which is composed of letters from the pattern, they are replaced by numbers.

Example: 
datePattern: "dd_MM_yyyy_HP_server" - > 21_07_2017_7P_server

and it should be 21_07_2017_HP__server

Help me please =)

**Comment by mattberther** [comment]
How about:

```
var transport = new winston.transports.DailyRotateFile({
  filename: '_HP_server',
  datePattern: 'dd_MM_yyyy',
  prepend: true
});
```
