### ISSUE TITLE
Log file error when running in root folder

### ISSUE THREAD

**Issue by TheKoopaKingdom** [winstonjs/winston-daily-rotate-file#84]
I'm trying to rotate log files in a Node app, but I'm getting an error about the file not being found.
The error:
```
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'logs/2017-08-19.log'
```
The relevant code:
```js
const winston = require('winston');
require('winston-daily-rotate-file');
const logger = new winston.Logger({
  transports: [
    new winston.transports.DailyRotateFile({
      level: 'debug',
      filename: 'logs/log',
      prepend: true
    })
  ],
  handleExceptions: true,
  humanReadableUnhandledException: true,
  exitOnError: false,
  meta: true,
});
```

In my development environment, it has no trouble creating any files, but in production, in the path `/opt/KoopaBot/`, this error occurs. I've tried starting the server with `sudo NODE_ENV=production node server.js` and starting it from a systemctl service that runs as root, but the error still persists.

I'm fairly certain that the script is being ran with root permissions, because [my other solution for log rotation](https://github.com/TheKoopaKingdom/discord-bot/commit/7582aa662affe3e737682aff6f23f0333e33e7c9) which also wrote log files to `/opt/KoopaBot/` worked fine under the same conditions.

**Comment by mattberther** [comment]
You're creating a folder called `logs` with your filename. This library expects the folder to exist. The error message you present indicates that it likely isnt. Try `mkdir /opt/KoopaBot/logs` and then try to run your logger agin.

**Comment by mattberther** [comment]
@TheKoopaKingdom 1.7.0 which was just pushed to npm supports the createTree option which will allow you to force the creation of the file tree.

**Comment by TheKoopaKingdom** [comment]
I ended up doing something different. I realized that `/opt/KoopaBot` didn't really *have* to be owned by root, if anything it's a security risk. So, I changed the
