### ISSUE TITLE
use moment to set timezone.

### ISSUE THREAD

**Issue by SwenChan** [winstonjs/winston-daily-rotate-file#86]
I have meet this issue:
I have some task running in docker and this is my every logs first record:
{"@message":"hello world","@timestamp":"2017-08-18 08:00:00:114","@fields":{"level":"info"}}
because my timestamps setting is
```javascript
Moment.tz.setDefault('Asia/Shanghai');
timestamp: () => Moment().format('YYYY-MM-DD HH:mm:ss:SSS')
```
and the log file will not rotate before 8 AM because in node docker image, timezone is not 'Asia/Shanghai' so ```new Date().getDay()``` is still yesterday and don't rotate the log file.
So, I really need this options to set logs timezone.
#85 
@mattberther

**Comment by SwenChan** [comment]
Is there anyone who can help with this pr? I just keep waiting for so long, and if this feature have some problem, please let me know and I can find some other way to deal with it. @mattberther @indexzero

**Comment by mattberther** [comment]
@SwenChan Your docker container should be setting the timezone appropriately, and not this library. This library assumes a properly configured container.

To learn how to set the timezone in your container look at http://tedwise.com/2015/05/02/setting-the-timezone-in-a-docker-image/ (assuming you're using a Debian/Ubuntu base). Alpine containers will set the timezone similarly.

**Comment by SwenChan** [comment]
Thanks a lot! I will find some other way to fix this. But I think it will be awesome for developer that if they can set timezone by themselves without modify the environment, whether bare metal or docker. 
By the way, I'm using alpha base ~~
