### ISSUE TITLE
DailyRotateFile - unresolved type

### ISSUE THREAD

**Issue by LukeXF** [winstonjs/winston-daily-rotate-file#87]
```
var winstonMain = require('winston');
require('winston-daily-rotate-file');

var transport = new winstonMain.transports.DailyRotateFile({
    // config
});
```

`DailyRotateFile` give me `Unresolved Type` in my editor, any suggestions?

**Comment by mattberther** [comment]
@LukeXF is the code not running, or is this just a matter of your editor presenting an error?

**Comment by LukeXF** [comment]
This is just the editor, frustrating because this is the only error in my IDE.

**Comment by mattberther** [comment]
@LukeXF can you provide some specifics on your editor (name, plugins, etc)? Maybe someone here has a solution.

**Comment by mattberther** [comment]
This is not an error with the transport. Closing due to lack of response.
