### ISSUE TITLE
log rotation feature crashes intermittently 

### ISSUE THREAD

**Issue by pose** [winstonjs/winston-daily-rotate-file#9]
> Originally reported by @nikdunn [here](https://github.com/winstonjs/winston/issues/768)

------

I have no idea if it is related to the other crash issues I've seen documented, but I am seeing:

Error: ENOENT, open '/work/server/server.log'

Every once in a while. In the directory there is a server.log.gz that is 0 bytes along with other log files that have been successfully rotated.

The issue seems to happen when logging frequency and content is high.

I've handled the uncaught exception, but there's not really anything I can do about it since the logger blew chunks.

I'm doing:
```
winston.add(winston.transports.File, {
    filename: __dirname + '/server.log',
    json: false,
    colorize: true,
    timestamp: true,
    maxsize: 10000000,
    maxFiles: 50,
    showLevel: true,
    tailable: true,
    zippedArchive: true,
});
winston.remove(winston.transports.Console);
```

**Comment by mattberther** [comment]
As I review this issue, it appears as though this is related to `winston.transports.File` and not `winston-daily-rotate-file`. Perhaps we should close this issue?

**Comment by nikdunn** [comment]
Yep.
