### ISSUE TITLE
winston.transports.DailyRotateFile is not a constructor

### ISSUE THREAD

**Issue by AChmieletzki** [winstonjs/winston-daily-rotate-file#90]
When I try the example setup, I run into an exception.

```
var winston = require('winston');
winston.cli();

var transport = new (winston.transports.DailyRotateFile)({
    filename: 'logs/log',
    datePattern: 'yyyy-MM-dd.',
    prepend:true,
    level: "verbose",
    maxDays:0
});

winston.add(transport);
```

Gives me:

> TypeError: winston.transports.DailyRotateFile is not a constructor
    at Object.<anonymous> (/home/project/Backend/node-server/logger.js:8:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/project/Backend/node-server/server.js:3:14)
    at Module._compile (module.js:570:32)

Node Version v6.10.3
NPM Version 3.10.10
Winston 2.3.1
Winston-Daily-Rotate-File 1.7.0

Running on Ubuntu 16.04.3

**Comment by mattberther** [comment]
I dont see `require('winston-daily-rotate-file');`

What happens with:

```
var winston = require('winston');
require('winston-daily-rotate-file');
winston.cli();

var transport = new (winston.transports.DailyRotateFile)({
    filename: 'logs/log',
    datePattern: 'yyyy-MM-dd.',
    prepend:true,
    level: "verbose",
    maxDays:0
});

winston.add(transport);
```

**Comment by AChmieletzki** [comment]
Oops sorry, forgot to include it in my post. But the issue persists.

I worked around it by downgrading winston to 1.x.x and removing 'winston-daily-rotate-file' requirement (because if I include it I get an error that winston needs to be 2.x.x)

As a side note, I'm using winston in a seperate .js file.

**Comment by mattberther** [comment]
Thanks, @AChmieletzki. I've managed to reproduce the issue. Now to identify a fix. :)

**Comment by mattberther** [comment]
@AChmieletzki I see the issue now. winston.add expects the constructor, not an instance. Try doing this instead:

```
var winston = require('winston');
require('winston-daily-rotate-file');
winston.cli();

winston.add(winston.transports.DailyRotateFile, {
  filename: 'logs/log',
  datePattern: 'yyyy-MM-dd.',
  prepend: true,
  level: 'verbose',
  maxDays: 0
});
```

**Comment by mgara** [comment]
Hello
Does this work ? 
const { format, createLogger, addColors, transports: winstonTransports } = require('winston');

require('winston-daily-rotate-file');

**Comment by mattberther** [comment]
You can also add the transport later by using `logger.add`, but yes, as you indicated the key is to use `createLogger`.

```
const logger = createLogger();
const rotateFileTransport = new (winstonTransports.DailyRotateFile)({
...
}):
logger.add(rotateFileTransport);
```

**Comment by chawax** [comment]
I had the same problem with latest version (Winston  3.3.3 and winston-daily-rotate-file 4.5.5) and could make it work this way :

```
import winston, { createLogger, transports, format } from 'winston';
import 'winston-daily-rotate-file'; // Add DailyRotateFile to Winston transports

const consoleTransport = new transports.Console({});

const dailyRotateFileTransport = new transports.DailyRotateFile({
      filename: 'requests-%DATE%.log',
      datePattern: 'YYYY-MM-DD-HH',
      zippedArchive: true,
      maxSize: '20m',
      maxFiles: '30d',
});

this.logger = createLogger({
      level: 'verbose',
     format: format.simple(),
      transports: [dailyRotateFileTransport, consoleTransport],
    });
```

**Comment by staplespeter** [comment]
I have also had this issue when using the instructions on https://github.com/winstonjs/winston-daily-rotate-file#readme

I had to use the default export from `winston-daily-rotate-file`:

```
import winston from "winston";
import winstonDailyFileTransport from 'winston-daily-rotate-file';

global.logger = winston.createLogger({
    transports: [
        new winstonDailyFileTransport({
            dirname: './logs/jest/',
            filename: 'test.%DATE%.log',
            maxFiles: '30d'
        })
    ]
});
```
