### ISSUE TITLE
transport.query hangs after first execution

### ISSUE THREAD

**Issue by TsvetomirGeorgiev** [winstonjs/winston-daily-rotate-file#92]
Queryng the log return results only the first time. Any attempt afterwards just hangs.

The issue happens because this line in the query prototype.

line: 294 ```var createdFiles = self._currentFiles;```

This creates a copy of the array on which you call ```createdFiles.shift()``` later on.
After the first execution the ```self._currentFiles``` is empty.
There is no condition to call the callback if the currentFiles are emplty. If I call this in an express middleware I would never get response from the route.

**Comment by TheHanna** [comment]
+1

Just experienced this issue while creating a small API for logging and viewing logs via expressjs + winston, and ran into this issue

**Comment by mattberther** [comment]
@TsvetomirGeorgiev @TheHanna Can you provide a simple code example that reproduces the problem, please?

**Comment by TheHanna** [comment]
@mattberther I'd be glad to later tonight.

**Comment by TheHanna** [comment]
@mattberther I've created a small demo that recreates the issue:

https://github.com/TheHanna/winston-daily-rotate-file-issue-92

**Comment by mattberther** [comment]
@TheHanna Thank you. :)

Can you and @TsvetomirGeorgiev both try #93 and see if this corrects the problems you're having? If so, I'll get a new version pushed to npm asap.

**Comment by TsvetomirGeorgiev** [comment]
@TheHanna  @mattberther, thanks for the lightning fast reaction! I would not be able to test anything untill next Wednesday but I've already tried the same approach you got and it worked. I would however also add  a check if the files array is empty and call the callback with empty result.

Thanks once again guys !!!

**Comment by mattberther** [comment]
Good catch. Just pushed a change to address this.

**Comment by mattberther** [comment]
Pushed to npm as 1.7.1

**Comment by TsvetomirGeorgiev** [comment]
Good job!

**Comment by TheHanna** [comment]
@mattberther Just confirmed via my example app that it works! Great stuff, thanks for the fast turnaround time!
